### ISSUE TITLE
[Bug]: Room DB doesn't shows error in compiler

### ISSUE THREAD

**Issue by bassem-saeed** [AndroidIDEOfficial/AndroidIDE#1039] opened 2023-06-14 18:13 UTC
### What happened?

When I add room database to my project the compiler executes this error:

```
Task :app:kaptDebugKotlin
Failed to load native library:sqlite-3.36.0-ceb5d390-d40f-43d6-bc08-f54df6e3af25-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.36.0-ceb5d390-d40f-43d6-bc08-f54df6e3af25-libsqlitejdbc.so: dlopen failed: library "libc.so.6" not found: needed by /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.36.0-ceb5d390-d40f-43d6-bc08-f54df6e3af25-libsqlitejdbc.so in namespace (default)
warning: Current JDK version 17-internal+0-adhoc..src has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.

> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

Note: I synchronized the project many times

### What's the expected behavior?

Send me the  **libc.so.6**  or another solution

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-15 17:08
Duplicate of #827.

**Closed by itsaky** 2023-06-15 17:08 UTC
Labels: bug
