### ISSUE TITLE
[Bug]: It crashs when I just open a normal project

### ISSUE THREAD

**Issue by 2980077544** [AndroidIDEOfficial/AndroidIDE#1119] opened 2023-07-18 07:28 UTC
### What happened?

It crashs when I just open a normal project.

### What's the expected behavior?

Crash...

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2101K9C
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta.internal.1+branch.dev.commit.263ce48.timestamp.20230716083526 (250)

 Stacktrace: 
java.lang.IllegalArgumentException: Syntax highlights query is invalid
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:125)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.log.LogLanguage.<init>(LogLanguage.kt:31)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:244)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:243)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:153)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:145)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.invoke$lambda$0(TaskExecutor.kt:63)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.$r8$lambda$IhA-YFhAfBBwhoc4NxFxsoc9sco(Unknown Source:0)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

 crash report
Manufacturer: Xiaomi
Device: M2101K9C
ABI: arm64-v8a
SDK version: 31
App version: v2.5.0-beta.internal.1+branch.dev.commit.263ce48.timestamp.20230716083526 (250)

 Stacktrace: 
java.lang.IllegalArgumentException: Syntax highlights query is invalid
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:125)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.log.LogLanguage.<init>(LogLanguage.kt:31)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:244)
	at com.itsaky.androidide.fragments.LogViewFragment$onViewCreated$2.invoke(LogViewFragment.kt:243)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:153)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readScheme$3.invoke(IDEColorSchemeProvider.kt:145)
	at com.itsaky.androidide.tasks.TaskExecutorKt$sam$com_itsaky_androidide_tasks_TaskExecutor_CallbackWithError$0.complete(Unknown Source:2)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.invoke$lambda$0(TaskExecutor.kt:63)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2.$r8$lambda$IhA-YFhAfBBwhoc4NxFxsoc9sco(Unknown Source:0)
	at com.itsaky.androidide.tasks.TaskExecutor$executeAsyncProvideError$2$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-18 07:44
Duplicate of #1108.

**Closed by itsaky** 2023-07-18 07:44 UTC
Labels: bug
