### ISSUE TITLE
[Bug]: Scrolling Always Crash

### ISSUE THREAD

**Issue by masfha** [AndroidIDEOfficial/AndroidIDE#542] opened 2022-10-19 12:47 UTC
### What happened?

If I add a variable it always crashes when I scroll...

### What's the expected behavior?

![Uploading Screenshot_2022-10-19-19-47-34-39_9ad8e654efd333b66ab21513aa36e36c.jpg…]()

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2461
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-d6c157f (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=98; index=100
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:292)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2382)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1300)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:578)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:177)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3978)
	at android.view.View.draw(View.java:22809)
	at android.view.View.updateDisplayListIfDirty(View.java:21663)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4588)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4561)
	at android.view.View.updateDisplayListIfDirty(View.java:21620)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4763)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4467)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3549)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2322)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9155)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:375)
	at android.view.Choreographer.doFrame(Choreographer.java:913)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-10-23 06:07
Dude, this is a duplicate of issue #537 which was also opened by you. 😐

**Closed by itsaky** 2022-10-23 06:07 UTC
Labels: bug
