### ISSUE TITLE
[Bug]: Deleting a text fragment causes a crash

### ISSUE THREAD

**Issue by modo1994** [AndroidIDEOfficial/AndroidIDE#717] opened 2023-01-02 04:22 UTC
### What happened?

Select a piece of text, click on the soft keyboard to delete, the program crashes, and it will reappear every time.

### What's the expected behavior?

What should I do to delete a piece of text

### What version of AndroidIDE you're using?

v2.1.3

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2011K2C
ABI: arm64-v8a
SDK version: 33
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(EditorInputConnection.java:133)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(EditorInputConnection.java:96)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl.lambda$commitText$16$com-android-internal-inputmethod-RemoteInputConnectionImpl(RemoteInputConnectionImpl.java:569)
	at com.android.internal.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda35.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-01-03 02:21
Duplicate of #613.

**Closed by itsaky** 2023-01-03 02:21 UTC
Labels: bug

**Comment by modo1994** [comment] 2023-01-04 00:10
Am I going to add 'sora-editor' to my app's dependencies?
