### ISSUE TITLE
[Bug]: Apk install dialogue not showing after build is successful.

### ISSUE THREAD

**Issue by amal6424** [AndroidIDEOfficial/AndroidIDE#480] opened 2022-09-29 03:09 UTC
### What happened?

After the build successful the installer dialogue not showing.

### What's the expected behavior?

No apk file specified in output listing file.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
EditorActivity            I   Gradle build service has been started... 
GradleBuildService        I   Starting tooling API server... 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
CachingProject            W   No tasks found in project '' 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectMessage(directory=/storage/emulated/0/AndroidIDEProjects/MyApplication, gradleInstallation=/data/data/com.itsaky.androidide/files/home/.gradle/wrapper/dists/gradle-7.4.2-bin/48ivgl02cpt2ed3fh9dbalvx8/gradle-7.4.2)  
ToolingApiErrorStream     E   SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle installation:  /data/data/com.itsaky.androidide/files/home/.gradle/wrapper/dists/gradle-7.4.2-bin/48ivgl02cpt2ed3fh9dbalvx8/gradle-7.4.2  
ToolingApiServer          D   StopWatch                  Connector created in 64ms  
ToolingApiServer          D   StopWatch                  Project connection established in 23ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --build-cache]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          D   StopWatch                  Project read successful in 26865ms  
ToolingApiServer          D   StopWatch                  Connection to project completed in 26963ms  
AndroidModule             I   Indexing sources and classpaths for project:  :app 
StopWatch                 D   Indexing sources completed in 74ms 
AndroidModule             D   Found 4 source files. 
StopWatch                 D   Indexing classpaths completed in 176ms 
AndroidModule             D   Found 1182 classpaths. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/android.jar 
StopWatch                 D   Indexing 1 bootclasspaths completed in 89ms 
..aultApiVersionsRegistry I   Creating API versions table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32 
WidgetTableRegistry       I   Creating widget table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/data/res/values/symbols.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-32/data/res/values/public.xml 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
StopWatch                 D   Indexing sources completed in 42ms 
AndroidModule             D   Found 4 source files. 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
SourceFileManager         I   Creating source file manager instance for module:  AndroidModule: :app 
ValuesTable               I   Took 10 ms to read 3 files in directory: /storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/res/values 
ValuesTableFactory        D   Created value tables for 1 resource directories in 20 ms 
DefaultActionsRegistry    I   Action 'Quick run' completed in 5ms 
ToolingApiServer          D   ToolingApiServerImpl       Received request to run tasks.  TaskExecutionMessage(projectPath=:, tasks=[assembleDebug], gradleInstallation=/data/data/com.itsaky.androidide/files/home/.gradle/wrapper/dists/gradle-7.4.2-bin/48ivgl02cpt2ed3fh9dbalvx8/gradle-7.4.2)  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle installation:  /data/data/com.itsaky.androidide/files/home/.gradle/wrapper/dists/gradle-7.4.2-bin/48ivgl02cpt2ed3fh9dbalvx8/gradle-7.4.2  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --build-cache]  
QuickRunAction            D   Installing APK(s) for variant: debug 
ApkMetadata               W   APK metadata null check failed. Metadata:  ApkMetadata{version=0, artifactType=null, applicationId='null', variantName='null', elements=null, elementType='null'} 
ApkMetadata               W   Invalid APK metadata:  ApkMetadata{version=0, artifactType=null, applicationId='null', variantName='null', elements=null, elementType='null'} 
QuickRunAction            E   No apk file specified in output listing file:  /storage/emulated/0/AndroidIDEProjects/MyApplication/app/build/intermediates/apk_ide_redirect_file/debug/redirect.txt 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-10-02 12:14
This is a duplicate of #470.

**Closed by itsaky** 2022-10-02 12:14 UTC
Labels: bug
