### ISSUE TITLE
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote7
ABI: arm64-v8a
SDK version: 29
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1958)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1990)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


### ISSUE THREAD

**Issue by Alux9907** [AndroidIDEOfficial/AndroidIDE#1068] opened 2023-07-08 20:57 UTC

**Comment by itsaky** [comment] 2023-07-09 02:50
Duplicate of #870.

**Closed by itsaky** 2023-07-09 02:50 UTC
