### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WolfGolf** [AndroidIDEOfficial/AndroidIDE#807] opened 2023-02-18 16:40 UTC
### What happened?

AndroidIDE crash report Manufacturer: HUAWEI Device: MRD-LX1F ABI: armeabi-v7a SDK version: 28 App version: v2.3.0-beta (230) Stacktrace: java.lang.IllegalStateException: GradleBuildService instance has been released at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40) at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932) at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964) at android.os.Handler.handleCallback(Handler.java:907) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:216) at android.app.ActivityThread.main(ActivityThread.java:7625) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

### What's the expected behavior?

AndroidIDE crash report Manufacturer: HUAWEI Device: MRD-LX1F ABI: armeabi-v7a SDK version: 28 App version: v2.3.0-beta (230) Stacktrace: java.lang.IllegalStateException: GradleBuildService instance has been released at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40) at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932) at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964) at android.os.Handler.handleCallback(Handler.java:907) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:216) at android.app.ActivityThread.main(ActivityThread.java:7625) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report Manufacturer: HUAWEI Device: MRD-LX1F ABI: armeabi-v7a SDK version: 28 App version: v2.3.0-beta (230) Stacktrace: java.lang.IllegalStateException: GradleBuildService instance has been released at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40) at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932) at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964) at android.os.Handler.handleCallback(Handler.java:907) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:216) at android.app.ActivityThread.main(ActivityThread.java:7625) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-02-19 04:23
Duplicate of #798.

**Closed by itsaky** 2023-02-19 04:23 UTC
Labels: bug
