### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Reza478** [AndroidIDEOfficial/AndroidIDE#915] opened 2023-04-01 08:10 UTC
AndroidIDE crash report
Manufacturer: SHARP
Device: SH-04L
ABI: arm64-v8a
SDK version: 30
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2002)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2034)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:8208)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:979)

**Comment by deepkrg17** [comment] 2023-04-01 08:29
Duplicate of #870

**Closed** 2023-04-05 04:52 UTC
