### ISSUE TITLE
[Bug]: ProcessCancelledException during signature help

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1531] opened 2023-12-03 05:24 UTC
### What happened?

   Crash when typing.

### What's the expected behavior?

I type variable in style: int var1,var2,var3 and else and if i dont save quick enough, it crashes. Behind the ; is one line comment as a note for now.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

Stacktrace:
com.itsaky.androidide.progress.ProcessCancelledException
	at com.itsaky.androidide.progress.ICancelChecker$Default.abortIfCancelled(Unknown Source:9)
	at com.itsaky.androidide.tasks.JobCancelChecker.abortIfCancelled(Unknown Source:5)
	at com.itsaky.androidide.lsp.java.providers.CancelableServiceProvider.abortIfCancelled(Unknown Source:2)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:40)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$2.invokeSuspend(Unknown Source:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-16 17:39
Duplicate of #1484.

**Closed by itsaky** 2023-12-16 17:39 UTC
Labels: bug
