### ISSUE TITLE
Crash info

### ISSUE THREAD

**Issue by ANONY4** [AndroidIDEOfficial/AndroidIDE#794] opened 2023-02-13 12:17 UTC
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH2343
ABI: arm64-v8a
SDK version: 33
App version: 2.1.4-beta (214)

 Stacktrace: 
java.lang.IllegalArgumentException: Value must be a reference to a drawable resource type. '@'
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.throwInvalidResType(basicParseUtils.kt:17)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:11)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ViewAdapter$createAttrHandlers$2.invoke(ViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at androidx.fragment.app.strictmode.FragmentStrictMode$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:65)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by deepkrg17** [comment] 2023-02-13 13:03
Duplicate of #744. Already fixed.

**Closed** 2023-02-13 13:03 UTC
