### ISSUE TITLE
IOOB when formatting XML file

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1425] opened 2023-11-05 16:18 UTC
### What happened?

This error was reported by another user, but I don't think he reported it here, this error occurs sometimes when we click on the format button in an XML file, I was lucky (or unlucky) when it happened in the first time I tried to reproduce, and 2 other times at different times 

Edit: I managed to capture the error on video

https://github.com/AndroidIDEOfficial/AndroidIDE/assets/93414086/11d45a74-4fc2-4876-8670-1acf9fcc9af1

### What's the expected behavior?

Not crash

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.5.3-beta (253)
CI Build : true
Branch : dev
Commit : 769e5d32d
Variant : armeabi-v7a (release)
SDK Version : 28
Supported ABIs : [armeabi-v7a, armeabi]
Manufacturer : LGE
Device : LM-X420

Stacktrace:
java.lang.ArrayIndexOutOfBoundsException: length=20; index=-1
	at io.github.rosemoe.sora.widget.EditorRenderer.drawLineNumber(Unknown Source:159)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawStuckLineNumbers(Unknown Source:158)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(Unknown Source:3236)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(Unknown Source:33)
	at android.view.View.draw(View.java:20277)
	at android.view.View.updateDisplayListIfDirty(View.java:19152)
	at android.view.View.draw(View.java:20005)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4186)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:28)
	at android.view.View.updateDisplayListIfDirty(View.java:19143)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4391)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4364)
	at android.view.View.updateDisplayListIfDirty(View.java:19112)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3506)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3303)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2653)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1572)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7632)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1020)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

 ```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abn-safita** [comment] 2023-11-06 05:26
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 22120RN86G
ABI: arm64-v8a
SDK version: 31
App version: v2.5.3-beta (253)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:900)
	at android.content.res.AssetManager.open(AssetManager.java:877)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:290)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:295)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1715)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by itsaky** [comment] 2023-11-06 12:59
> The IDE logs showed this error again in JSONRpc, I don't know if it is related

It simply means the project was not initialized but task execution was requested.

**Comment by itsaky** [comment] 2023-11-17 14:01
Can you check if this happens with the [latest CI build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6904920164)? There were some [changes](https://github.com/Rosemoe/sora-editor/commit/6d761d6b37c25b002d413433a40293f032708467) made to the sora-editor repository regarding this.

**Comment by Rafael2616** [comment] 2023-11-17 14:21
Of course, I will test

**Comment by Rafael2616** [comment] 2023-11-17 14:41
> Can you check if this happens with the [latest CI build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/6904920164)? There were some [changes](https://github.com/Rosemoe/sora-editor/commit/6d761d6b37c25b002d413433a40293f032708467) made to the sora-editor repository regarding this.

Yes, that no longer happened 👍

**Comment by itsaky** [comment] 2023-11-17 14:42
Okay. Closing this as completed.

**Closed by itsaky** 2023-11-17 14:42 UTC
Labels: bug
