### ISSUE TITLE
[Bug]: Crash when using action "Implement abstract class method (s)"

### ISSUE THREAD

**Issue by itsvks19** [AndroidIDEOfficial/AndroidIDE#905] opened 2023-03-27 21:00 UTC
### What happened?

Application crashed when I am using action "Implement abstract class method (s)".

### What's the expected behavior?

Crash should not happen.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-F127G
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta.internal.1+branch.dev.commit.3206065.timestamp.20230326172327 (241)

 Stacktrace: 
java.lang.ClassCastException: androidx.constraintlayout.widget.ConstraintLayout$LayoutParams cannot be cast to android.widget.RelativeLayout$LayoutParams
	at com.itsaky.androidide.fragments.sheets.ProgressSheet.onViewCreated(ProgressSheet.java:56)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1825)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment] 2023-03-27 22:45
Duplicate of #904.

**Comment by itsvks19** [comment] 2023-03-27 22:52
@deepkrg17 Only log output is same. Not way to reproduce.

**Comment by itsaky** [comment] 2023-03-28 03:37
Duplicate of #904 (fixed in a948cd4).

**Closed by itsaky** 2023-03-28 03:37 UTC
Labels: bug

**Comment by itsvks19** [comment] 2023-03-28 08:48
I am using 3a1f5ff. Not fixed.

**Comment by itsaky** [comment] 2023-03-28 09:04
From the stack trace, it's clear that you're using CI build for [`3206065`](https://github.com/AndroidIDEOfficial/AndroidIDE/commit/3206065):
```
App version: v2.4.1-beta.internal.1+branch.dev.commit.3206065.timestamp.20230326172327 (241)
```
In commit 3a1f5ff, there are no references to `RelativeLayout.LayoutParams` in `ProgressSheet`. I don't think this issue exists anymore. However, if you are sure about this, can you provide us a way to reproduce this error?
