### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Iyanuhacks** [AndroidIDEOfficial/AndroidIDE#1042] opened 2023-06-15 00:08 UTC
### What happened?

AndroidIDE crash report
Manufacturer: TECNO MOBILE LIMITED
Device: TECNOBB2
ABI: armeabi-v7a
SDK version: 27
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1662)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1691)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6552)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

### What's the expected behavior?

It supposed to display all build successfully

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-15 17:05
Duplicate of #870.

**Closed by itsaky** 2023-06-15 17:05 UTC
Labels: bug
