### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dujani** [AndroidIDEOfficial/AndroidIDE#612] opened 2022-11-14 01:20 UTC
AndroidIDE crash report
Manufacturer: HUAWEI
Device: ELS-N04
ABI: arm64-v8a
SDK version: 29
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.lookup.ServiceRegisteredException
	at com.itsaky.androidide.lookup.internal.DefaultLookup.registerOrUpdate(DefaultLookup.java:19)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:22)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2193)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2225)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by itsaky** [comment] 2022-11-14 02:24
Duplicate of #465.

**Closed by itsaky** 2022-11-14 02:24 UTC
