### ISSUE TITLE
[Feature]: request fitur format code like a CodeAssists app

### ISSUE THREAD

**Issue by thianganz21** [AndroidIDEOfficial/AndroidIDE#1779] opened 2024-03-31 03:22 UTC
### Issue Checklist

- [x] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

request fitur format code like a CodeAssists app
CodeAssist can automatically format code neatly by simply pressing the format option

### Use Case

This feature is very helpful in tidying up messy code

### Benefits

the benefits are many one of which can make it easier for users and make the application more powerful

**Comment by BanDroid** [comment] 2024-03-31 03:57
we already have code formatter

**Comment by itsaky** [comment] 2024-04-07 14:12
AndroidIDE already has code formatter for Java and XML files. If you're talking about a customizable Java formatter, then this is a duplicate of #1466.

**Closed as not planned by itsaky** 2024-04-07 14:12 UTC
Labels: feature
