### ISSUE TITLE
[Bug]: When notification is clicked it closes project

### ISSUE THREAD

**Issue by CyberXCoder-6649** [AndroidIDEOfficial/AndroidIDE#1548] opened 2023-12-12 08:34 UTC
### What happened?

When clicked on notification it closes project

### What's the expected behavior?

It should open project rather than going to HomeActivity

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment] 2023-12-12 15:41
This problem is a duplicate of one I already reported here https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1202

**Comment by Rafael2616** [comment] 2023-12-12 16:16
As I said, there is already a similar problem open, so the owner will probably close this one when he checks the issues opened

**Comment by CyberXCoder-6649** [comment] 2023-12-12 16:49
Ok so let's close it

**Closed** 2023-12-12 16:49 UTC
Labels: bug
