### ISSUE TITLE
[Bug]: Code completion problem

### ISSUE THREAD

**Issue by ms458** [AndroidIDEOfficial/AndroidIDE#855] opened 2023-03-12 06:56 UTC
### What happened?

Automatic code completion is always invalid
![Screenshot_2023-03-12-14-54-02-667_com itsaky androidide](https://user-images.githubusercontent.com/108029807/224529326-7af9c89d-46e7-433c-9a0f-49fd07ef128d.jpg)

### What's the expected behavior?

It should be complete automatically at any time

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-03-12 07:00
> Automatic code completion is always invalid

Could you elaborate the issue?

**Comment by ms458** [comment] 2023-03-12 07:07
For example, when you write code in the run() method, autofill will fail and you won't be able to bring up a code prompt
![Screenshot_2023-03-12-15-03-14-555_com itsaky androidide](https://user-images.githubusercontent.com/108029807/224529770-68fd3aaf-292e-4dc4-afb4-90f23c6898c0.jpg)

**Comment by itsaky** [comment] 2023-03-12 07:11
Actually, this issue has already been fixed in commit bdd119d63153ece5acba811945ac0ac0a30a2f62 ([CI build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/4332318663)). It will be included in the next release (#836).

**Closed by itsaky** 2023-03-12 07:11 UTC
Labels: bug

**Comment by itsaky** [comment] 2023-03-12 07:13
Duplicate of #823.
