### ISSUE TITLE
New issue found 

### ISSUE THREAD

**Issue by code-with-prabhat** [AndroidIDEOfficial/AndroidIDE#684] opened 2022-12-25 06:54 UTC
AndroidIDE crash report
Manufacturer: realme
Device: RMX3171
ABI: arm64-v8a
SDK version: 30
App version: 2.1.3-beta (213)

 Stacktrace: 
java.lang.NullPointerException
	at com.itsaky.androidide.fragments.LogViewFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:19)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by itsaky** [comment] 2022-12-26 02:06
Duplicate of #682.

**Closed by itsaky** 2022-12-26 02:06 UTC
