### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by DjilaliDEV** [AndroidIDEOfficial/AndroidIDE#1835] opened 2024-06-20 20:20 UTC
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G998B

Stacktrace:
android.system.ErrnoException: fstat failed: ENOENT (No such file or directory)
	at libcore.io.Linux.fstat(Native Method)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:195)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.IoBridge.open(IoBridge.java:563)
 Caused by: java.io.FileNotFoundException: /storage/emulated/0/AndroidIDEProjects/constraintCalculator/.androidide/editor/openedFiles.json: fstat failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at kotlinx.coroutines.AwaitKt.writeText$default(Unknown Source:23)
	at com.itsaky.androidide.viewmodel.EditorViewModel$writeOpenedFiles$1.invokeSuspend(Unknown Source:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at androidx.work.Worker$2.run(Unknown Source:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by itsaky** [comment] 2024-06-21 02:30
Duplicate of #1781

**Closed as not planned by itsaky** 2024-06-21 02:30 UTC
