### ISSUE TITLE
AndroidIDE crash report

### ISSUE THREAD

**Issue by HackFoxnew** [AndroidIDEOfficial/AndroidIDE#980] opened 2023-05-19 08:32 UTC
AndroidIDE crash report
Manufacturer: TECNO MOBILE LIMITED
Device: TECNOKE7
ABI: arm64-v8a
SDK version: 29
App version: v2.4.1-beta.internal.1+branch.dev.commit.e450713.timestamp.20230513183010 (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleServiceBinder.getService(GradleServiceBinder.kt:35)
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:37)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7684)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by itsaky** [comment] 2023-05-19 09:45
Duplicate of #870.

**Closed by itsaky** 2023-05-19 09:45 UTC
