### ISSUE TITLE
[Feature]: Please add an option for the editor to be in full screen.

### ISSUE THREAD

**Issue by JohnOlowe** [AndroidIDEOfficial/AndroidIDE#1486] opened 2023-11-19 03:16 UTC
### Feature description

![Screenshot_20231119-035511](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/121398818/291975a9-a7f5-4fac-8d9b-a1bb1197d333)
When the phone is in landscape mode, the keyboard fills up the whole screen. It would be better if there is an option to set the editor to full screen mode.

### What version of AndroidIDE you're using?

v2.6.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-11-19 03:18
Duplicate of #1106.

**Closed by itsaky** 2023-11-19 03:18 UTC
Labels: feature
