### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by asalphotostudio** [AndroidIDEOfficial/AndroidIDE#1809] opened 2024-05-15 18:52 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2010J19CG

Stacktrace:
java.lang.IllegalStateException: No TreeSitterLanguage found for type log
	at androidx.navigation.NavController$handleDeepLink$2.invoke(SourceFile:21)
	at androidx.navigation.NavController$handleDeepLink$2.invoke(SourceFile:252)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider$readSchemeAsync$1.invokeSuspend(Unknown Source:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.AtomicKt.resumeCancellableWith(Unknown Source:138)
	at _COROUTINE._BOUNDARY.startCoroutineCancellable$default(Unknown Source:13)
	at kotlinx.coroutines.AbstractCoroutine.start(Unknown Source:81)
	at okio.Base64.launch(Unknown Source:23)
	at okio.Base64.launch$default(Unknown Source:14)
	at com.itsaky.androidide.editor.schemes.IDEColorSchemeProvider.readSchemeAsync$default(Unknown Source:84)
	at com.itsaky.androidide.fragments.output.LogViewFragment.onViewCreated(Unknown Source:89)
	at com.itsaky.androidide.fragments.output.AppLogFragment.onViewCreated(Unknown Source:5)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:255)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:148)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(Unknown Source:1070)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(Unknown Source:81)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(Unknown Source:31)
	at androidx.fragment.app.BackStackRecord.commitNow(Unknown Source:9)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(Unknown Source:181)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(Unknown Source:2)
	at androidx.recyclerview.widget.ChildHelper.addView(Unknown Source:40)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(Unknown Source:219)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:33)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:818)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:73)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:71)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:7)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:60)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(Unknown Source:391)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(Unknown Source:203)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:40)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:57)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:871)
	at android.view.View.layout(View.java:23580)
	at android.view.ViewGroup.layout(ViewGroup.java:6455)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3311)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2275)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9002)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1182)
	at android.view.Choreographer.doCallbacks(Choreographer.java:972)
	at android.view.Choreographer.doFrame(Choreographer.java:895)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1164)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8322)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

    

### Expected behavior

Хз

### Version name

2.7.1

### Download source

GitHub

**Comment by itsaky** [comment] 2024-05-18 15:51
Duplicate of #1666

**Closed as not planned by itsaky** 2024-05-18 15:51 UTC
Labels: bug
