### ISSUE TITLE
Can't open terminal after installation. I was following the instructions from the AndroidIDE web and can't find any solution on internet 

### ISSUE THREAD

**Issue by alsianmubeen** [AndroidIDEOfficial/AndroidIDE#1366] opened 2023-10-05 15:15 UTC
AndroidIDE crash report
Manufacturer: asus
Device: ASUS_I005DA
ABI: arm64-v8a
SDK version: 33
App version: v2.5.3-beta (253)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:904)
	at android.content.res.AssetManager.open(AssetManager.java:881)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1780)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:291)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:296)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1783)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1772)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1185)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1658)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1625)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by MrIkso** [comment] 2023-10-06 01:26
https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1315#issuecomment-1719684259

**Comment by itsaky** [comment] 2023-10-06 02:39
Duplicate of #1315.

**Closed by itsaky** 2023-10-06 02:39 UTC
