### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chandafa** [AndroidIDEOfficial/AndroidIDE#1467] opened 2023-11-14 19:14 UTC
### What happened?

AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiNote9Pro

Stacktrace:
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1498)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1501)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

    

### What's the expected behavior?

AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiNote9Pro

Stacktrace:
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1498)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1501)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

    

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.0-beta (260)
CI Build : true
Branch : main
Commit : 34d7e34e4
Variant : arm64-v8a (release)
SDK Version : 31
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiNote9Pro

Stacktrace:
androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1498)
 Caused by: java.util.concurrent.CompletionException: androidx.startup.StartupException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/./include
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(Unknown Source:1501)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raredeveloper** [comment] 2023-11-14 19:24
Make sure that you're installing AndroidIDE for the primary user. Multiple users are not supported. #1450

**Comment by itsaky** [comment] 2023-11-14 19:33
Duplicate of #1450.

**Closed by itsaky** 2023-11-14 19:33 UTC
Labels: bug, duplicate
