### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by awkarinss31** [AndroidIDEOfficial/AndroidIDE#1081] opened 2023-07-10 13:56 UTC
### What happened?

AndroidIDE crash report and Lag

### What's the expected behavior?

Legs and crashes when opening .java

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: realme
Device: RMX2103
ABI: arm64-v8a
SDK version: 30
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2147)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2179)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-10 14:14
Duplicate of #870.

**Closed by itsaky** 2023-07-10 14:14 UTC
Labels: bug
