### ISSUE TITLE
[Feature]: ndk support for all abi

### ISSUE THREAD

**Issue by LIBBBhhh** [AndroidIDEOfficial/AndroidIDE#1492] opened 2023-11-23 17:45 UTC
### Feature description

a great replacement for android studio, but not enough for complete happiness, ndk for all abi

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment] 2023-11-24 00:49
Duplicate of #162.

**Closed** 2023-11-24 03:40 UTC
Labels: feature
