### ISSUE TITLE
Carsh AndroidIDE app

### ISSUE THREAD

**Issue by gopal444** [AndroidIDEOfficial/AndroidIDE#1664] opened 2024-01-17 10:27 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

When I close my all activities than crash 

### Expected behavior

AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3395

Stacktrace:
android.system.ErrnoException: fstat failed: ENOENT (No such file or directory)
	at libcore.io.Linux.fstat(Native Method)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:195)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.IoBridge.open(IoBridge.java:563)
 Caused by: java.io.FileNotFoundException: /storage/emulated/0/AndroidIDEProjects/Quizy/Online Quizz/OnlineQuiz/.androidide/editor/openedFiles.json: fstat failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at kotlin.TuplesKt.writeText$default(Unknown Source:23)
	at com.itsaky.androidide.viewmodel.EditorViewModel$writeOpenedFiles$1.invokeSuspend(Unknown Source:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

    

### Version name

Latest version 
![Screenshot_2024-01-17-15-55-17-12_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/52792752/94249dd9-7b27-42e1-9978-e421f296fc4d)

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.0-beta (27001)
CI Build : false
Branch : HEAD
Commit : 062d240e9
Variant : arm64-v8a (release)
Build type : OFFICIAL
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3395

Stacktrace:
android.system.ErrnoException: fstat failed: ENOENT (No such file or directory)
	at libcore.io.Linux.fstat(Native Method)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:195)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:261)
	at libcore.io.IoBridge.open(IoBridge.java:563)
 Caused by: java.io.FileNotFoundException: /storage/emulated/0/AndroidIDEProjects/Quizy/Online Quizz/OnlineQuiz/.androidide/editor/openedFiles.json: fstat failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at kotlin.TuplesKt.writeText$default(Unknown Source:23)
	at com.itsaky.androidide.viewmodel.EditorViewModel$writeOpenedFiles$1.invokeSuspend(Unknown Source:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at org.greenrobot.eventbus.AsyncPoster.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
```

**Comment by itsaky** [comment] 2024-01-18 14:34
Duplicate of #1621

**Closed by itsaky** 2024-01-18 14:34 UTC
Labels: bug
