### ISSUE TITLE
[Feature]:Add kotlin code auto complete 

### ISSUE THREAD

**Issue by abodinagdat16** [AndroidIDEOfficial/AndroidIDE#1062] opened 2023-07-01 18:52 UTC
### Feature description

please add kotlin lsp to the editor......i know this request submitted before one year ago but Only you can develop ot well....

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment] 2023-07-02 01:19
Duplicate of #211.

**Closed** 2023-07-02 02:07 UTC
Labels: feature
