### ISSUE TITLE
Split screen support

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1728] opened 2024-02-16 03:48 UTC
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Android feature that this app does not support,  allows to use 2 apps at same time without needing to press the Overview Button(Swuare) on Navbar many time. https://we.tl/t-0p73gRiaMm here is further description.

### Use Case

Wanna rewrite text but you dont wannna keep reopening two apps or dont have two phones.

### Benefits

Faster for productivity and any app i seen on my phone that i checked, suports it. Mine will get it too

**Comment by itsaky** [comment] 2024-02-16 05:34
Duplicate of #1221

**Closed as not planned by itsaky** 2024-02-16 05:34 UTC
Labels: duplicate, feature
