### ISSUE TITLE
[Bug]: Crash when i open Cosmicide-rewrite

### ISSUE THREAD

**Issue by scto** [AndroidIDEOfficial/AndroidIDE#1036] opened 2023-06-14 01:16 UTC
### What happened?

Crash after try open cosmicide-rewrite

### What's the expected behavior?

No crash

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Google
Device: Pixel3XL
ABI: arm64-v8a
SDK version: 31
App version: v2.4.1-beta.internal.1+branch.a99a87704d7394f7107a1e37970b5d2f6667a895.commit.a99a877.timestamp.20230612202859 (241)

 Stacktrace: 
java.lang.IllegalArgumentException: Syntax highlights query is invalid
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:125)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.<init>(KotlinLanguage.kt:30)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.FACTORY$lambda$0(KotlinLanguage.kt:33)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.$r8$lambda$AzoEE-HedI8ey8DrFqnPQ2fZJYM(Unknown Source:0)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage$$ExternalSyntheticLambda0.create(Unknown Source:0)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguageProvider.forFile(TreeSitterLanguageProvider.kt:34)
	at com.itsaky.androidide.editor.ui.IDEEditor.createLanguage(IDEEditor.java:991)
	at com.itsaky.androidide.editor.ui.IDEEditor.setupLanguage(IDEEditor.java:947)
	at com.itsaky.androidide.ui.editor.CodeEditorView.postRead(CodeEditorView.java:163)
	at com.itsaky.androidide.ui.editor.CodeEditorView.lambda$new$0$com-itsaky-androidide-ui-editor-CodeEditorView(CodeEditorView.java:131)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-15 17:21
Duplicate of #1032.

**Closed by itsaky** 2023-06-15 17:21 UTC
Labels: bug
