### ISSUE TITLE
[Bug]:  ConstraintLayout not displaying widgets in editor (xml palette)

### ISSUE THREAD

**Issue by BtAbdul** [AndroidIDEOfficial/AndroidIDE#896] opened 2023-03-23 05:13 UTC
### What happened?

The ConstraintLayout not displayed in editor. it shows blank but widgets are showing in hierarchy.

Screenshots:
Editor: 
[https://ibb.co/HXMfDVQ](url)

hierarchy:
[https://ibb.co/5BhnRWx](url)

xml:
[https://ibb.co/5BhnRWx](url)

### What's the expected behavior?

it must show previews of layout like other linearlayout etc

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment] 2023-03-23 06:23
Androidx widgets currently not supported

**Comment by deepkrg17** [comment] 2023-03-25 12:45
@itsaky You may close this as duplicate of #212

**Closed** 2023-03-25 12:46 UTC
Labels: bug
