### ISSUE TITLE
Git error

### ISSUE THREAD

**Issue by KMODs-dev** [AndroidIDEOfficial/AndroidIDE#1768] opened 2024-03-19 21:00 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

No virtual method readNBytes(I)[B in class Ljava/io/FilelnputStream; or its super classes (declaration of 'java.io.FileInputStream' appears in /apex/com.android.art/javalib/ core-oj.jar)

### Expected behavior

I hoped it would work 

### Version name

Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : motorola
Device : motog(9)play

### Download source

GitHub

**Comment by itsaky** [comment] 2024-03-20 03:59
Duplicate of #1720

**Closed as not planned by itsaky** 2024-03-20 03:59 UTC
Labels: bug, duplicate
