### ISSUE TITLE
[Bug]: app freeze

### ISSUE THREAD

**Issue by ask9027** [AndroidIDEOfficial/AndroidIDE#1349] opened 2023-09-29 15:33 UTC
### What happened?

while type some thing and automatically dont accept any input except touch input but when want to do others things in app it freeze for infinite time. 

### What's the expected behavior?

App should not freeze.

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Relevant log output

```shell
No Log
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-10-02 03:09
Duplicate of #1209.

**Closed by itsaky** 2023-10-02 03:09 UTC
Labels: bug
