### ISSUE TITLE
[Bug]: A Crash

### ISSUE THREAD

**Issue by Tanya7z** [AndroidIDEOfficial/AndroidIDE#821] opened 2023-02-26 02:07 UTC
### What happened?

Crash while editing

### What's the expected behavior?

Crash while editing

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: 22041216C
ABI: arm64-v8a
SDK version: 33
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=90
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:34)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:111)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:113)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:34)
	at android.view.View.draw(View.java:23483)
	at android.view.View.updateDisplayListIfDirty(View.java:22301)
	at android.view.View.draw(View.java:23193)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4602)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4360)
	at android.view.View.updateDisplayListIfDirty(View.java:22290)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
	at android.view.View.updateDisplayListIfDirty(View.java:22241)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4968)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4657)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3854)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2563)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9605)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8133)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-02-26 03:23
Duplicate of #771.

**Closed by itsaky** 2023-02-26 03:23 UTC
Labels: bug
