### ISSUE TITLE
[Bug]: Parameter crash

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1557] opened 2023-12-16 09:16 UTC
### What happened?

How to update androidIDE? And another is this problem, when i call function, it crashes when i type parameters. I type parenthesis and xant give all values coz it crash. Need to do it via text editor

### What's the expected behavior?

Call function ok. No rush needed and i cam complete it. Modifying param values to existing call is fine but writing new call of function with 2+params, it sucka more than with regular text editor.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

Stacktrace:
com.itsaky.androidide.progress.ProcessCancelledException
	at com.itsaky.androidide.progress.ICancelChecker$Default.abortIfCancelled(Unknown Source:9)
	at com.itsaky.androidide.tasks.JobCancelChecker.abortIfCancelled(Unknown Source:5)
	at com.itsaky.androidide.lsp.java.providers.CancelableServiceProvider.abortIfCancelled(Unknown Source:2)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:40)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$2.invokeSuspend(Unknown Source:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-16 10:09
Duplicate of issue #1531, which was opened by you. I already warned you about this in #1542.

**Closed by itsaky** 2023-12-16 10:09 UTC
Labels: bug
