### ISSUE TITLE
 [Bug] Unable to create directory

### ISSUE THREAD

**Issue by deadcombo** [AndroidIDEOfficial/AndroidIDE#877] opened 2023-03-18 14:00 UTC
```
AndroidIDE crash report
Manufacturer: Google
Device: Pixel7Pro
ABI: arm64-v8a
SDK version: 33
App version: v2.4.0-beta (240)

 Stacktrace: 
com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:333)
 Caused by: java.util.concurrent.CompletionException: com.itsaky.androidide.utils.BootstrapInstaller$InstallationException: Unable to create directory: /data/data/com.itsaky.androidide/files/usr/bin
	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:336)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1712)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1704)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:294)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1657)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1595)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by itsaky** [comment] 2023-03-19 17:42
Duplicate of #766.

**Closed by itsaky** 2023-03-19 17:42 UTC
