### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AndresNorm** [AndroidIDEOfficial/AndroidIDE#1615] opened 2024-01-09 03:52 UTC
AndroidIDE Crash Report
Version : v2.7.0-beta (27002)
CI Build : false
Branch : HEAD
Commit : 4f4bde4d2
Variant : arm64-v8a (release)
Build type : UNOFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.0-beta
F-Droid Version code : 27002
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : vivo1819

Stacktrace:
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:139)
	at android.app.Dialog.<init>(Dialog.java:193)
	at androidx.activity.ComponentDialog.<init>(Unknown Source:5)
	at androidx.appcompat.app.AppCompatDialog.<init>(Unknown Source:22)
	at androidx.appcompat.app.AlertDialog.<init>(Unknown Source:4)
	at org.commonmark.internal.BlockContent.create(Unknown Source:10)
	at com.google.android.material.dialog.MaterialAlertDialogBuilder.create(Unknown Source:0)
	at org.commonmark.internal.BlockContent.show(Unknown Source:0)
	at androidx.room.SharedSQLiteStatement$stmt$2.invoke(SourceFile:69)
	at com.itsaky.androidide.fragments.MainFragment$doClone$cloneJob$1.invokeSuspend(Unknown Source:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at androidx.work.Worker$2.run(Unknown Source:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)

**Comment by itsaky** [comment] 2024-01-09 04:32
Duplicate of #1608.

**Closed by itsaky** 2024-01-09 04:32 UTC
