### ISSUE TITLE
[Bug]: When open file *.kts in ide, the app force close

### ISSUE THREAD

**Issue by SzHzSH** [AndroidIDEOfficial/AndroidIDE#1032] opened 2023-06-11 08:45 UTC
### What happened?

The app force close when i open file build.gradle.kts in ide

### What's the expected behavior?

Normally editing build.gradle.kts with syntax highlights in ide to edit my hobby project 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: V2031
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta.internal.1+branch.dev.commit.e8bc312.timestamp.20230611062119 (241)

 Stacktrace: 
java.lang.IllegalArgumentException: Syntax highlights query is invalid
	at io.github.rosemoe.sora.editor.ts.TsLanguageSpec.<init>(TsLanguageSpec.kt:125)
	at com.itsaky.androidide.editor.schemes.LanguageSpecProvider.getLanguageSpec(LanguageSpecProvider.kt:51)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguage.<init>(TreeSitterLanguage.kt:58)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.<init>(KotlinLanguage.kt:30)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.FACTORY$lambda$0(KotlinLanguage.kt:33)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage.$r8$lambda$AzoEE-HedI8ey8DrFqnPQ2fZJYM(Unknown Source:0)
	at com.itsaky.androidide.editor.language.kotlin.KotlinLanguage$$ExternalSyntheticLambda0.create(Unknown Source:0)
	at com.itsaky.androidide.editor.language.treesitter.TreeSitterLanguageProvider.forFile(TreeSitterLanguageProvider.kt:34)
	at com.itsaky.androidide.editor.ui.IDEEditor.createLanguage(IDEEditor.java:991)
	at com.itsaky.androidide.editor.ui.IDEEditor.setupLanguage(IDEEditor.java:947)
	at com.itsaky.androidide.ui.editor.CodeEditorView.postRead(CodeEditorView.java:163)
	at com.itsaky.androidide.ui.editor.CodeEditorView.lambda$new$0$com-itsaky-androidide-ui-editor-CodeEditorView(CodeEditorView.java:131)
	at com.itsaky.androidide.ui.editor.CodeEditorView$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-15 17:23
Duplicate of #1016.

**Closed by itsaky** 2023-06-15 17:23 UTC
Labels: bug
