### ISSUE TITLE
way libgdx object delete?

### ISSUE THREAD

**Issue by jdhdhsbjd6454543** [AndroidIDEOfficial/AndroidIDE#1104] opened 2023-07-14 15:25 UTC
### Feature description

way libgdx object delete?

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-14 16:56
> way libgdx object delete?

Can you explain the feature?

**Comment by jdhdhsbjd6454543** [comment] 2023-07-18 00:37
> > way libgdx object delete?
> 
> Can you explain the feature?

为什么新版本把libgdx模板删掉了？

**Comment by 2980077544** [comment] 2023-07-18 07:39
已经有人提过了#1099

**Comment by itsaky** [comment] 2023-07-18 07:43
> 为什么新版本把libgdx模板删掉了？

This is a duplicate of #1099. Also, instead of everyone else using a translator to read your messages, you should use a translator instead.

**Closed by itsaky** 2023-07-18 07:43 UTC
Labels: feature
