### ISSUE TITLE
I was quitting and opening the app and changing the phone's theme and this happened

### ISSUE THREAD

**Issue by MohamedAnwer75** [AndroidIDEOfficial/AndroidIDE#1586] opened 2023-12-27 14:08 UTC
### What happened?

Same the title

### What's the expected behavior?

.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : 2203129G

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Unknown Source:54)
	at android.app.Instrumentation.callActivityOnPause(Unknown Source:0)
	at android.app.ActivityThread.performPauseActivityIfNeeded(Unknown Source:20)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(Unknown Source:124)
	at android.app.ActivityThread.performPauseActivity(Unknown Source:82)
	at android.app.ActivityThread.handlePauseActivity(Unknown Source:19)
	at android.app.servertransaction.PauseActivityItem.execute(Unknown Source:20)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:32)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:79)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-27 15:42
Duplicate of #1498.

**Closed by itsaky** 2023-12-27 15:42 UTC
Labels: bug
