### ISSUE TITLE
AndroidIDE crash 

### ISSUE THREAD

**Issue by Infinity918172929273773** [AndroidIDEOfficial/AndroidIDE#1784] opened 2024-04-03 18:45 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

when I know this message occurred

### Expected behavior

solve this problem

### Version name

v2.7.1-beta (27102)

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : dev
Commit : ae1bd6f42
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : INFINIX MOBILITY LIMITED
Device : InfinixX682B

Stacktrace:
java.lang.OutOfMemoryError: Failed to allocate a 603979784 byte allocation with 25165824 free bytes and 166MB until OOM, target footprint 387589856, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3257)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
	at java.lang.StringBuilder.append(StringBuilder.java:203)
	at kotlin.TuplesKt.createIndent(Unknown Source:32)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:188)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(Unknown Source:2300)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2809)
	at android.view.View.dispatchKeyEvent(View.java:13398)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1942)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:457)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1839)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3956)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at androidx.room.util.FileUtil.dispatchKeyEvent(Unknown Source:10)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(Unknown Source:18)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(Unknown Source:22)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:371)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5639)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5502)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5005)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5058)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5024)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5164)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5032)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5221)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5005)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5058)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5024)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5032)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5005)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7832)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7801)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7749)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4773)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7684)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by itsaky** [comment] 2024-04-07 14:06
Duplicate of #1694

**Closed as not planned by itsaky** 2024-04-07 14:06 UTC
Labels: bug, duplicate
