### ISSUE TITLE
I hope i can custom the action I run and also support maven

### ISSUE THREAD

**Issue by glowingstone124** [AndroidIDEOfficial/AndroidIDE#1710] opened 2024-02-05 15:18 UTC
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

If I can custom my build or run command, everything will be different! And also, my java project  depends on maven, but this ide supports Gradle only.

### Use Case

Build custom projects

### Benefits

More usage scenarios

**Comment by itsaky** [comment] 2024-02-05 15:26
> If I can custom my build or run command, everything will be different!

The ability to customize the tasks that are run using the `Quick run` button has already been requested in #1674.

> And also, my java project depends on maven, but this ide supports Gradle only.

There are no plans to add support for Maven projects, and I don't think there will be.

**Comment by itsaky** [comment] 2024-02-05 15:27
Duplicate of #1674

**Closed as completed by itsaky** 2024-02-05 15:27 UTC
Labels: duplicate, feature

**Comment by BanDroid** [comment] 2024-02-05 15:34
> my java project  depends on maven, but this ide supports Gradle only.

you could try to convert your maven project to gradle by intializing it

```bash
bash gradlew init
```

you could pick to import all maven settings to gradle config
