### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cjsi15** [AndroidIDEOfficial/AndroidIDE#1224] opened 2023-08-23 14:07 UTC
AndroidIDE crash report
Manufacturer: HONOR
Device: CRT-LX2
ABI: arm64-v8a
SDK version: 31
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5405)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@aa57c81: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5425)
	at android.app.ActivityThread.access$3300(ActivityThread.java:279)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2576)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:9000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by itsaky** [comment] 2023-08-23 15:37
Duplicate of #1195.

**Closed by itsaky** 2023-08-23 15:37 UTC
