### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shariatanim** [AndroidIDEOfficial/AndroidIDE#1263] opened 2023-09-03 21:55 UTC
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8
ABI: arm64-v8a
SDK version: 30
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:887)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(Unknown Source:144)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(Unknown Source:306)
	at io.github.rosemoe.sora.text.Content.insertInternal(Unknown Source:317)
	at io.github.rosemoe.sora.text.Content.replace(SourceFile:2)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:54)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(Unknown Source:327)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(Unknown Source:94)
	at io.github.rosemoe.sora.widget.CodeEditor.pasteText(Unknown Source:39)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:1)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:7)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:907)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(Unknown Source:10)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(Unknown Source:12)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:28)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(Unknown Source:5)
	at com.itsaky.androidide.fragments.CrashReportFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:83)
	at android.view.View.performClick(View.java:7507)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7484)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28689)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8
ABI: arm64-v8a
SDK version: 30
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:887)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(Unknown Source:144)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(Unknown Source:306)
	at io.github.rosemoe.sora.text.Content.insertInternal(Unknown Source:317)
	at io.github.rosemoe.sora.text.Content.replace(SourceFile:2)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:54)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(Unknown Source:327)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(Unknown Source:94)
	at io.github.rosemoe.sora.widget.CodeEditor.pasteText(Unknown Source:39)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:1)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:7)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:907)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(Unknown Source:10)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(Unknown Source:12)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:28)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(Unknown Source:5)
	at com.itsaky.androidide.fragments.CrashReportFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:83)
	at android.view.View.performClick(View.java:7507)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7484)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28689)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8
ABI: arm64-v8a
SDK version: 30
App version: v2.5.3-beta (253)

 Stacktrace: 
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:887)
	at com.itsaky.androidide.editor.ui.EditorCompletionWindow.requireCompletion(Unknown Source:144)
	at io.github.rosemoe.sora.widget.CodeEditor.afterInsert(Unknown Source:306)
	at io.github.rosemoe.sora.text.Content.insertInternal(Unknown Source:317)
	at io.github.rosemoe.sora.text.Content.replace(SourceFile:2)
	at io.github.rosemoe.sora.widget.CodeEditor.commitText(Unknown Source:54)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitTextInternal(Unknown Source:327)
	at io.github.rosemoe.sora.widget.EditorInputConnection.commitText(Unknown Source:94)
	at io.github.rosemoe.sora.widget.CodeEditor.pasteText(Unknown Source:39)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:1)
	at com.itsaky.androidide.actions.editor.CutAction.execAction(SourceFile:7)
	at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda0.run(Unknown Source:907)
	at com.blankj.utilcode.util.ThreadUtils.runOnUiThread(Unknown Source:10)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(Unknown Source:12)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:28)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(Unknown Source:5)
	at com.itsaky.androidide.fragments.CrashReportFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:83)
	at android.view.View.performClick(View.java:7507)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:9)
	at android.view.View.performClickInternal(View.java:7484)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28689)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-09-04 14:55
Duplicate of #1194.

**Closed by itsaky** 2023-09-04 14:55 UTC
Labels: bug
