### ISSUE TITLE
[Bug]:You ate my code!!!!!!!!!!

### ISSUE THREAD

**Issue by yz-gm** [AndroidIDEOfficial/AndroidIDE#1390] opened 2023-10-21 16:34 UTC
### What happened?

The interface is unresponsive when writing code!!!!!
You ate my code!!!And it has appeared several times!!!!!

My Info
![Screenshot_2023-10-22-00-32-13-78_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/65427441/00847b29-5ace-44ad-92a1-ddde1d72af30)

![Screenshot_2023-10-22-00-24-29-55_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/65427441/f90bf5dc-4012-4bef-9f42-8fcd2c7db4b9)
![Screenshot_2023-10-22-00-19-46-18_9ad8e654efd333b66ab21513aa36e36c](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/65427441/0c76dc76-48d2-4b40-9096-563b89b4f155)

### What's the expected behavior?

speed fix!!!!

### What version of AndroidIDE you're using?

v2.5.3

### Relevant log output

```shell
I didn't get any logs.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-10-22 03:51
Duplicate of #1209.

**Closed by itsaky** 2023-10-22 03:51 UTC
Labels: bug
