### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by andihasan97** [AndroidIDEOfficial/AndroidIDE#434] opened 2022-09-15 01:09 UTC
### What happened?

AndroidIDE crash report
Manufacturer: vivo
Device: vivo1901
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.progressindicator.LinearProgressIndicator com.itsaky.androidide.databinding.ActivityEditorBinding.buildProgressIndicator' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$onProjectInitialized$19$com-itsaky-androidide-EditorActivity(EditorActivity.java:934)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda16.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

### What's the expected behavior?

Repair 

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: vivo1901
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.progressindicator.LinearProgressIndicator com.itsaky.androidide.databinding.ActivityEditorBinding.buildProgressIndicator' on a null object reference
	at com.itsaky.androidide.EditorActivity.lambda$onProjectInitialized$19$com-itsaky-androidide-EditorActivity(EditorActivity.java:934)
	at com.itsaky.androidide.EditorActivity$$ExternalSyntheticLambda16.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-09-21 06:18
Duplicate of #257.

**Closed by itsaky** 2022-09-21 06:18 UTC
Labels: bug
