### ISSUE TITLE
[Bug] 2.6.0 File tree panel too wide when on landscape orientation

### ISSUE THREAD

**Issue by EmiyaSyahriel** [AndroidIDEOfficial/AndroidIDE#1490] opened 2023-11-21 14:26 UTC
### What happened?

![Screenshot_20231121-204952](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/24495564/66a67df4-5e04-4992-abff-f577f2eaacb0)

## Tested on
- Nokia T20, 2000x1200 @ ~280ppi (Smallest UI Scale), Android 13
- Nokia X30, 2400x1080 @ ~420ppi (Smallest UI Scale), Android 13

### What's the expected behavior?

On previous version (2.5.3-beta) when both panels were still separated at the left or right of screen, both of them only occupies "enough" screen space that you can still see the code clearly. I think you can use the panel size from the previous version with a little bit adjustment since it's now a combined panel.

Or maybe you can give user the option to choose whether they want the panel to be wide or narrow (or maybe adaptive based on directory depth).

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-11-21 14:44
Duplicate of #1430.

**Closed by itsaky** 2023-11-21 14:44 UTC
Labels: bug

**Comment by EmiyaSyahriel** [comment] 2023-11-21 23:06
I'm sorry, I'm not noticing this one when searching around duplicate issues 😅. Anyway, Thank you for your hard work.
