### ISSUE TITLE
[BUG]: IDE CRASH ON LONG WRITES!

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1542] opened 2023-12-08 14:39 UTC
### What happened?

Always even with code assist when i write loong code real fast and there is obviously some erors too, if game doesnt crash, app crashes while editing. I gota save like every few words in such, now i added big coment to know wha to do and crash. It hapened with list before. HOW TO REPRODUCE: leave an errror and code elsewhere over 5 seconds and crash u will see. Today hapened twice. Other file with error leave unsaved. I think autosave or syntax checker causes the issue. Maybe option to dusable checking the code before compile might do the fix

### What's the expected behavior?

When i edit long, i dont lose progress by crash.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A202F

Stacktrace:
com.itsaky.androidide.progress.ProcessCancelledException
	at com.itsaky.androidide.progress.ICancelChecker$Default.abortIfCancelled(Unknown Source:9)
	at com.itsaky.androidide.tasks.JobCancelChecker.abortIfCancelled(Unknown Source:5)
	at com.itsaky.androidide.lsp.java.providers.CancelableServiceProvider.abortIfCancelled(Unknown Source:2)
	at com.itsaky.androidide.lsp.java.JavaLanguageServer.signatureHelp(Unknown Source:40)
	at com.itsaky.androidide.editor.ui.IDEEditor$signatureHelp$2.invokeSuspend(Unknown Source:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:93)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pavel5750cz** [comment] 2023-12-08 14:44
Hapened again.  Been writin coment and then added ,, and more text and i pressed space at end, thinking wgat to type nexxt again and i will have to use text editor coz it suck write text

**Comment by itsaky** [comment] 2023-12-13 16:21
Dude, this is a duplicate of issue #1531, which you opened. Don't go creating creating duplicates of your own issues.

**Closed by itsaky** 2023-12-13 16:21 UTC
Labels: bug
