### ISSUE TITLE
[Feature]: Flutter support

### ISSUE THREAD

**Issue by mesflit** [AndroidIDEOfficial/AndroidIDE#930] opened 2023-04-06 17:30 UTC
### Feature description

get flutter support

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-04-07 16:51
Duplicate of #197.

**Closed by itsaky** 2023-04-07 16:51 UTC
Labels: feature
