### ISSUE TITLE
[Bug]: AndroidIDE crashed upon closing project

### ISSUE THREAD

**Issue by danielpaul-123** [AndroidIDEOfficial/AndroidIDE#1150] opened 2023-07-25 06:46 UTC
### What happened?

AndroidIDE crashed when the project was closed 

### What's the expected behavior?

AndroidIDE crashed when I tried to close the project. App version v2.5.1-beta

### What version of AndroidIDE you're using?

v2.5.0

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: CPH1979
ABI: arm64-v8a
SDK version: 30
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4723)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@321e728: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4743)
	at android.app.ActivityThread.access$2100(ActivityThread.java:299)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2231)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:8312)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-25 18:01
Duplicate of #1132.

**Closed by itsaky** 2023-07-25 18:01 UTC
Labels: bug
