### ISSUE TITLE
[Bug]: app crash 

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#815] opened 2023-02-24 18:31 UTC
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi6Pro
ABI: arm64-v8a
SDK version: 28
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi6Pro
ABI: arm64-v8a
SDK version: 28
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### What version of AndroidIDE you're using?

v2.2.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-02-25 12:48
Duplicate of #798.

**Closed by itsaky** 2023-02-25 12:48 UTC
Labels: bug
