### ISSUE TITLE
[Bug]: App not launching after build is complete

### ISSUE THREAD

**Issue by elidrissidev** [AndroidIDEOfficial/AndroidIDE#573] opened 2022-10-31 19:14 UTC
### What happened?

After clicking the "Play" button to build the app, the build succeeds but the app is not launching automatically (nor installing for the first launch). I have to launch it manually.

If it matters, I'm using Android 12 (MiUI).

### What's the expected behavior?

When the build is complete, the app should start automatically.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, --info]  
QuickRunAction            D   Installing APK(s) for variant: debug 
ApkMetadata               W   APK metadata null check failed. Metadata:  ApkMetadata{version=0, artifactType=null, applicationId='null', variantName='null', elements=null, elementType='null'} 
ApkMetadata               W   Invalid APK metadata:  ApkMetadata{version=0, artifactType=null, applicationId='null', variantName='null', elements=null, elementType='null'} 
QuickRunAction            E   No apk file specified in output listing file:  /storage/emulated/0/AndroidIDEProjects/MyApplication/app/build/intermediates/apk_ide_redirect_file/debug/redirect.txt
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-11-01 01:41
Duplicate of #470. This issue was fixed in recent commits.

As you're using debug builds, you could try updating to the latest build. If the issue still exists, then reopen the issue.

**Closed by itsaky** 2022-11-01 01:41 UTC
Labels: bug
