### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Denxter** [AndroidIDEOfficial/AndroidIDE#499] opened 2022-10-05 02:15 UTC
### What happened?

AndroidIDE crash report
Manufacturer: HUAWEI
Device: AQM-LX1
ABI: arm64-v8a
SDK version: 29
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.lookup.ServiceRegisteredException
	at com.itsaky.androidide.lookup.internal.DefaultLookup.registerOrUpdate(DefaultLookup.java:19)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:22)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2066)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2098)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: HUAWEI
Device: AQM-LX1
ABI: arm64-v8a
SDK version: 29
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.lookup.ServiceRegisteredException
	at com.itsaky.androidide.lookup.internal.DefaultLookup.registerOrUpdate(DefaultLookup.java:19)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:22)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2066)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2098)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HUAWEI
Device: AQM-LX1
ABI: arm64-v8a
SDK version: 29
App version: 2.1.2-beta (212)

 Stacktrace: 
com.itsaky.androidide.lookup.ServiceRegisteredException
	at com.itsaky.androidide.lookup.internal.DefaultLookup.registerOrUpdate(DefaultLookup.java:19)
	at com.itsaky.androidide.EditorActivity$1.onServiceConnected(EditorActivity.java:22)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2066)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2098)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment] 2022-10-05 02:23
This bug is already reported and you have checked "this issue hasn't been reported" !
Duplicate of #465 .

**Comment by Denxter** [comment] 2022-10-05 03:58
Sorry I don't knkw

**Closed** 2022-10-05 04:16 UTC
Labels: bug
