### ISSUE TITLE
[Bug]: There was a bug in the xml editor when I went to change the button background color

### ISSUE THREAD

**Issue by rubensfox20** [AndroidIDEOfficial/AndroidIDE#768] opened 2023-01-28 23:03 UTC
### What happened?

There was a bug in the xml editor when I went to change the button background color

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: samsung
Device: SM-A025M
ABI: armeabi-v7a
SDK version: 31
App version: v2.2.0-beta (220)

 Stacktrace: 
java.lang.IllegalArgumentException: Value must be a reference to a drawable resource type. '@'
	at com.itsaky.androidide.inflater.internal.utils.BasicParseUtilsKt.throwInvalidResType(basicParseUtils.kt:17)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable(AbstractParser.kt:11)
	at com.itsaky.androidide.inflater.AbstractParser.parseDrawable$default(AbstractParser.kt:15)
	at com.itsaky.androidide.inflater.internal.adapters.ViewAdapter$createAttrHandlers$2.invoke(ViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.IViewAdapter.applyInternal(IViewAdapter.kt:20)
	at com.itsaky.androidide.inflater.IViewAdapter$apply$1.invoke(IViewAdapter.kt:10)
	at com.itsaky.androidide.inflater.IViewAdapter.doApply(IViewAdapter.kt:62)
	at com.itsaky.androidide.inflater.IViewAdapter.apply(IViewAdapter.kt:17)
	at com.itsaky.androidide.inflater.internal.ViewImpl.applyAttribute(ViewImpl.kt:40)
	at com.itsaky.androidide.uidesigner.fragments.AttrValueEditorFragment$showAttrInfo$1$2.invoke(AttrValueEditorFragment.kt:65)
	at com.sun.tools.javac.main.JavaCompiler$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:35)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### What version of AndroidIDE you're using?

v2.2.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-01-31 09:41
Duplicate of #744.

**Closed by itsaky** 2023-01-31 09:41 UTC
Labels: bug
