### ISSUE TITLE
[Bug]: Whole code has error line and after some time ide crash. 

### ISSUE THREAD

**Issue by Rajdave-dev** [AndroidIDEOfficial/AndroidIDE#554] opened 2022-10-26 13:56 UTC
### What happened?

Ide crashed after sometime while fixing errors. 

### What's the expected behavior?

No crash. 

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: vivo
Device: V2059
ABI: arm64-v8a
SDK version: 31
App version: 2.1.2-beta_main-ba9c7c9 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=94
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:292)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2382)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1300)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:578)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:177)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3978)
	at android.view.View.draw(View.java:22929)
	at android.view.View.updateDisplayListIfDirty(View.java:21767)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4603)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4576)
	at android.view.View.updateDisplayListIfDirty(View.java:21718)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:561)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:669)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4815)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3667)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2383)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9306)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1186)
	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
	at android.view.Choreographer.doFrame(Choreographer.java:912)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1171)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment] 2022-10-27 16:43
It also happens with me while editing large files.

**Comment by itsaky** [comment] 2022-10-27 16:44
Duplicate of #537.

**Closed by itsaky** 2022-10-27 16:44 UTC
Labels: bug
