### ISSUE TITLE
[Bug]: Throws an exception while background

### ISSUE THREAD

**Issue by arunbhattarai** [AndroidIDEOfficial/AndroidIDE#907] opened 2023-03-28 02:08 UTC
### What happened?

Crashes while ide is in background.

### What's the expected behavior?

Should not have crashed while in background.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi8
ABI: arm64-v8a
SDK version: 29
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1958)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1990)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-03-28 03:37
Duplicate of #870.

**Closed by itsaky** 2023-03-28 03:37 UTC
Labels: bug
