### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kentemman** [AndroidIDEOfficial/AndroidIDE#431] opened 2022-09-08 17:18 UTC
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2012K11AG
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'com.itsaky.androidide.fragments.sheets.ProgressSheet com.itsaky.androidide.fragments.sheets.ProgressSheet.setMessage(java.lang.String)' on a null object reference
	at com.itsaky.androidide.fragments.WizardFragment.setMessage(WizardFragment.java:512)
	at com.itsaky.androidide.fragments.WizardFragment.onProcessTask(WizardFragment.java:466)
	at com.itsaky.androidide.utils.ProjectWriter.lambda$notifyTask$1(ProjectWriter.java:242)
	at com.itsaky.androidide.utils.ProjectWriter$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by itsaky** [comment] 2022-09-21 06:24
Duplicate of #227.

**Closed by itsaky** 2022-09-21 06:24 UTC
