### ISSUE TITLE
[Bug]: Crashing, Lagging In Letest Dev Build

### ISSUE THREAD

**Issue by extronteam** [AndroidIDEOfficial/AndroidIDE#1374] opened 2023-10-09 02:57 UTC
### What happened?

worst experience ever on Android ide it's soo laggy, it crashes after I move any linear in preview option, i don't love this app ANYMORE it just crashes and lag is wonderful I can't even type a single word in dev build 😊

### What's the expected behavior?

It should be smoother(I can't even type a single word smoothly), it shouldn't crash while editing fragment in preview page

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-10-28 10:07
A similar kind of issue was fixed recently, so this might be a duplicate of the same.

Also, if the IDE crashes, you need to at least provide the stack trace or logs.

**Closed by itsaky** 2023-10-28 10:07 UTC
Labels: bug
