### ISSUE TITLE
Logsender failing to bind

### ISSUE THREAD

**Issue by stacoder** [AndroidIDEOfficial/AndroidIDE#1856] opened 2024-07-25 12:09 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

I am facing an issue where I fail to see the logs of debug build. I always see a Toast saying "Failed to bind to AndroidIDE"
Here are the specs of my device.

Version : v2.7.1-beta (27101)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : armeabi-v7a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 28
Supported ABIs : [armeabi-v7a, armeabi]
Manufacturer : ITEL MOBILE LIMITED
Device : itelW6004P

### Expected behavior

To be able to view logs

### Version name

Version : v2.7.1-beta (27101)

### Download source

GitHub

**Comment by PrashantRawatCoder** [comment] 2024-07-25 14:16
I also have this issue,
**Many Times** it bind successfully but some time it shows nothing in APP log . Screen just get empty.

**Comment by Wjxfi** [comment] 2024-07-28 13:59
Same

**Comment by itsaky** [comment] 2024-07-28 16:17
Duplicate of #1599

**Closed as not planned by itsaky** 2024-07-28 16:17 UTC
Labels: bug
