### ISSUE TITLE
App FC

### ISSUE THREAD

**Issue by Otang45** [AndroidIDEOfficial/AndroidIDE#576] opened 2022-11-01 10:52 UTC
### What happened?

Fc while editing file

### What's the expected behavior?

?

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8
ABI: arm64-v8a
SDK version: 29
App version: 2.1.2-beta_main-a76eec2 (212)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=90; index=94
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:292)
	at io.github.rosemoe.sora.widget.EditorRenderer.measureText(EditorRenderer.java:2382)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawDiagnosticIndicators(EditorRenderer.java:1300)
	at io.github.rosemoe.sora.widget.EditorRenderer.drawView(EditorRenderer.java:578)
	at io.github.rosemoe.sora.widget.EditorRenderer.draw(EditorRenderer.java:177)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:3978)
	at android.view.View.draw(Unknown Source:52)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:188)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ViewGroup.recreateChildDisplayList(Unknown Source:21)
	at android.view.ViewGroup.dispatchGetDisplayList(Unknown Source:21)
	at android.view.View.updateDisplayListIfDirty(Unknown Source:77)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(Unknown Source:27)
	at android.view.ThreadedRenderer.updateRootDisplayList(Unknown Source:7)
	at android.view.ThreadedRenderer.draw(Unknown Source:9)
	at android.view.ViewRootImpl.draw(Unknown Source:463)
	at android.view.ViewRootImpl.performDraw(Unknown Source:112)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:2861)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:31)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:79)
	at android.view.Choreographer.doFrame(Unknown Source:182)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-11-01 11:09
Duplicate of #537.

**Closed by itsaky** 2022-11-01 11:09 UTC
Labels: bug
