### ISSUE TITLE
Absturz im hintergrund

### ISSUE THREAD

**Issue by Torefemy** [AndroidIDEOfficial/AndroidIDE#1563] opened 2023-12-18 03:55 UTC
### What happened?

Android IDE ist abgestürzt

### What's the expected behavior?

Im hintergrund offen bleiben

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-G960F

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8518)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1618)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5065)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5075)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5026)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4978)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-18 03:58
Duplicate of #1498.

**Closed by itsaky** 2023-12-18 03:58 UTC
Labels: bug
