### ISSUE TITLE
[Feature]: auto complete

### ISSUE THREAD

**Issue by PetersonIhmes** [AndroidIDEOfficial/AndroidIDE#1247] opened 2023-08-31 06:57 UTC
### Feature description

The app is simply wonderful and really fulfills what it promises but could improve it with auto completion for both Kotlin and Java and XML because apps that already have this option Another suggestion is to issue the last project to stay open without having to open it again every time you close the app

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BanDroid** [comment] 2023-08-31 06:59
duplicate of #211

**Closed** 2023-09-01 03:12 UTC
Labels: feature
