### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by selkw** [AndroidIDEOfficial/AndroidIDE#1829] opened 2024-06-10 02:36 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

i just change the app theme

### Expected behavior

i dont know, just change the app theme and then its crashing

### Version name

2.7.1 beta (27102)

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : M2102J20SG

Stacktrace:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1405)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:422)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:154)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1581)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1347)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1313)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.applyWindowAttributes(Unknown Source:152)
	at com.itsaky.androidide.editor.ui.AbstractPopupWindow.show(Unknown Source:25)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:224)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:21)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8289)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by itsaky** [comment] 2024-06-11 00:14
Duplicate of #1752

**Closed as not planned by itsaky** 2024-06-11 00:14 UTC
Labels: bug
