### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LsSketch** [AndroidIDEOfficial/AndroidIDE#1233] opened 2023-08-25 15:43 UTC
### What happened?

AndroidIDE crash report
Manufacturer: realme
Device: RMX2020
ABI: arm64-v8a
SDK version: 29
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4444)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@34bee65: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4464)
	at android.app.ActivityThread.access$2000(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

### What's the expected behavior?

...

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: realme
Device: RMX2020
ABI: arm64-v8a
SDK version: 29
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4444)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@34bee65: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4464)
	at android.app.ActivityThread.access$2000(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-08-25 16:03
Duplicate of #1195.

**Closed by itsaky** 2023-08-25 16:03 UTC
Labels: bug
