### ISSUE TITLE
Flash back when closing the project

### ISSUE THREAD

**Issue by inkwise** [AndroidIDEOfficial/AndroidIDE#1581] opened 2023-12-25 22:37 UTC
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : vivo
Device : V2158A

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.closeAll(Unknown Source:43)
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.onDestroy(Unknown Source:75)
	at android.app.Activity.performDestroy(Activity.java:8554)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1394)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5560)
 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5575)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5604)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2384)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by itsaky** [comment] 2023-12-26 03:45
Duplicate of #1498.

**Closed** 2023-12-26 03:46 UTC
