### ISSUE TITLE
[Bug]: Consuming lot of ram even phone memory is low

### ISSUE THREAD

**Issue by someonespcl** [AndroidIDEOfficial/AndroidIDE#1465] opened 2023-11-14 04:34 UTC
### What happened?

ANDROID IDE consuming lot of ram even the phone memory is low.
I faced a lot of freeze and lag even I my phone rebooted it self because ide not releasing memory when phone memory is low, which causes high ram consumption and low performance.
You might not experience in high end mobiles, but those who are having 4GB, 6GB Ram and mid range processor faces this issue a lot.
In low memory situation app is not crashing but it is continuously consuming ram, due to this Android system is not killing the app process.
Try to analyse the main cause and fix it ASAP.

### What's the expected behavior?

It should release the memory when phones memory is low.
While writing/editing the .XML files it should not lag.
For those who are having low ram and mid range processor, it should work efficiently without causing lag with limited features or full.

### What version of AndroidIDE you're using?

v2.6.0

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-11-14 09:08
Duplicate of #1279.

**Closed by itsaky** 2023-11-14 09:08 UTC
Labels: bug
