### ISSUE TITLE
Quando voces vão adicionar pra mostrar as cir3s no cores.xml [Feature]: 

### ISSUE THREAD

**Issue by JWJIW** [AndroidIDEOfficial/AndroidIDE#1052] opened 2023-06-19 15:04 UTC
### Feature description

![20230619_120348](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/86896232/28f5c11c-7bef-4837-81a2-19815d89f651)
 

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-19 15:06
Duplicate of #902

**Closed as not planned** 2023-06-19 15:06 UTC
Labels: duplicate, feature
