### ISSUE TITLE
What happened?!

### ISSUE THREAD

**Issue by jayxdcode** [AndroidIDEOfficial/AndroidIDE#1836] opened 2024-06-21 13:13 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

The app crashed when i close many tabs/fies at once (more than 7)

### Expected behavior

when i `close others` the app crashed. i let more than 7 tabs open and when i clear others other than what im currently working, it crashed and showed me the stacktrace

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3263

### Download source

F-Droid

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : realme
Device : RMX3263

Stacktrace:
android.system.ErrnoException: fstat failed: ENOENT (No such file or directory)
	at libcore.io.Linux.fstat(Native Method)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:106)
	at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:175)
	at libcore.io.ForwardingOs.fstat(ForwardingOs.java:106)
	at libcore.io.IoBridge.open(IoBridge.java:481)
 Caused by: java.io.FileNotFoundException: /storage/emulated/0/AndroidIDEProjects/Music/.androidide/editor/openedFiles.json: fstat failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at kotlinx.coroutines.AwaitKt.writeText$default(Unknown Source:23)
	at com.itsaky.androidide.viewmodel.EditorViewModel$writeOpenedFiles$1.invokeSuspend(Unknown Source:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:120)
	at androidx.work.Worker$2.run(Unknown Source:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
```

**Comment by itsaky** [comment] 2024-06-28 01:47
Duplicate of #1781

**Closed as not planned by itsaky** 2024-06-28 01:47 UTC
Labels: bug
