### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by huang030925** [AndroidIDEOfficial/AndroidIDE#1270] opened 2023-09-07 06:32 UTC
运行任务 : [assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Observed package id 'tools' in inconsistent location '/data/data/com.itsaky.androidide/files/home/android-sdk/cmdline-tools/latest' (Expected '/data/data/com.itsaky.androidide/files/home/android-sdk/tools')

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to find Build Tools revision 33.0.3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by BanDroid** [comment] 2023-09-07 06:50
change buildToolsVersion from 33.0.3 to 33.0.2 or 34.0.0 or just remove it

**Comment by itsaky** [comment] 2023-09-07 11:52
Duplicate of #1232.

**Closed by itsaky** 2023-09-07 11:52 UTC
