### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by LittlerWorm** [AndroidIDEOfficial/AndroidIDE#1866] opened 2024-08-01 19:58 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Error creating proyect

### Expected behavior

AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OnePlus
Device : KB2003

Stacktrace:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1480)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:424)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:154)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1581)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1346)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1312)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.applyWindowAttributes(Unknown Source:152)
	at com.itsaky.androidide.editor.ui.AbstractPopupWindow.show(Unknown Source:25)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:224)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:21)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

    

### Version name

Version : v2.7.1-beta (27102)
CI Build : false
Branch : HEAD
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : true
F-Droid Version : v2.7.1-beta
F-Droid Version code : 27102
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OnePlus
Device : KB2003

### Download source

F-Droid

**Comment by itsaky** [comment] 2024-09-01 11:40
Duplicate of #1752

**Closed as not planned by itsaky** 2024-09-01 11:40 UTC
Labels: bug
