### ISSUE TITLE
[Bug]: XML Designer will not display certain elements

### ISSUE THREAD

**Issue by AButterLamp** [AndroidIDEOfficial/AndroidIDE#1544] opened 2023-12-10 15:47 UTC
### What happened?

When i use the UI designer, it displays this error message:
![Screenshot_20231210-153610](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/145221959/69636b39-a525-4cd4-a3d6-a19e8f5193e6)

Here is the xml:
![Screenshot_20231210-153558~2](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/145221959/aad05d88-1074-4c90-ad78-26c3d2a92b72)

For other XML files it works, for example:
![Screenshot_20231210-154313](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/145221959/cb89c99b-21c3-403b-b1e8-df3f9ecdbfb7)
![Screenshot_20231210-154351](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/145221959/fb012a5e-0067-41e6-b7c6-d2f8efb37059)

But when the app compiles, it all works properly , and all the elements render

I am using [androidide-v2.6.1-beta-arm64-v8a-release.apk]

### What's the expected behavior?

The Designer UI Properly displays the elements 

### What version of AndroidIDE you're using?

v2.6.0

### Relevant log output

```shell
GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Connected to Gradle build service 
ToolingServerRunner       I   Starting tooling API server... 
EditorActivity            D   No variant selection information available. Default build variants will be selected. 
EditorActivity            D   Is project initialized: false 
EditorActivity            D   Sending init request to tooling server.. 
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
ToolingApiServer          D   ToolingApiMain             Server started. Will run until shutdown message is received...  
ToolingApiServer          D   ToolingApiServerImpl       Got initialize request  InitializeProjectParams(directory=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp, gradleDistribution=GradleDistributionParams(type=GRADLE_WRAPPER, value=), androidParams=AndroidInitializationParams(variantSelections={}))  
ToolingApiServer          I   ToolingApiMain             Checking gradle wrapper availability...  
ToolingApiServer          I   ToolingApiMain             Gradle wrapper is available  
ToolingApiErrorStream     E   SLF4J: No SLF4J providers were found. 
ToolingApiErrorStream     E   SLF4J: Defaulting to no-operation (NOP) logger implementation 
ToolingApiErrorStream     E   SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. 
ToolingApiServer          I   ToolingApiServerImpl       Using Gradle wrapper for build...  
ToolingApiServer          D   StopWatch                  Connector created in 331ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: true 
ToolingApiServer          D   StopWatch                  Project connection established in 109ms  
ToolingApiServer          D   ToolingApiMain             Arguments from tooling client:  [--init-script, /data/data/com.itsaky.androidide/files/home/.androidide/init/init.gradle, -Pandroid.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2, -Pandroidide.logsender.isEnabled=true, --info]  
ToolingApiServer          W   ProjectReader              Starting build. See build output for more details...  
ToolingApiServer          D   ProjectReader              Build action executed. Result:  com.itsaky.androidide.tooling.impl.internal.ProjectImpl@4d8bd933  
ToolingApiServer          D   StopWatch                  Project read successful in 104108ms  
ToolingApiServer          D   StopWatch                  Connection to project completed in 104590ms  
EditorActivity            D   onBuildStatusChanged: isInitializing: true, isBuildInProgress: false 
CachingProject            D   No sync issues. 
StopWatch                 D   Transform project proxy completed in 1160ms 
ProjectManagerImpl        I   Found 0 project sync issues: [] 
AndroidModule             I   Indexing sources and classpaths for project:  :app 
JavaModule                I   Indexing sources and classpaths for project:  : 
StopWatch                 D   Indexing sources completed in 0ms 
JavaModule                D   Found 0 source files. 
StopWatch                 D   Indexing classpaths completed in 1ms 
JavaModule                D   Found 0 classpaths. 
StopWatch                 D   Indexing sources completed in 90ms 
AndroidModule             D   Found 14 source files. 
StopWatch                 D   Indexing classpaths completed in 1016ms 
AndroidModule             D   Found 2492 classpaths. 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/android.jar 
StopWatch                 D   Indexing 1 bootclasspaths completed in 309ms 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/symbols.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/public-staging.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/public-final.xml 
ResourceTableRegistry     W   Failed to compile /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33/data/res/values/config_telephony.xml 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
..aultApiVersionsRegistry I   Creating API versions table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33 
WidgetTableRegistry       I   Creating widget table for platform dir: /data/data/com.itsaky.androidide/files/home/android-sdk/platforms/android-33 
StopWatch                 D   Read resources for module : :app completed in 6948ms 
StopWatch                 D   Setup project completed in 8373ms 
StopWatch                 D   Indexing sources completed in 1ms 
JavaModule                D   Found 0 source files. 
StopWatch                 D   Indexing sources completed in 46ms 
AndroidModule             D   Found 14 source files. 
ILanguageServerRegistry   D   Dispatching ProjectInitializedEvent to language servers... 
..ngJarFileSystemProvider D   Clearing cached JAR file system for path:  /storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/R.jar 
SourceFileManager         I   Creating source file manager instance for module:  AndroidModule: :app 
EditorActivity            D   onBuildStatusChanged: isInitializing: false, isBuildInProgress: false 
EditorActivity            I   Opening file at index:  0  file:   /storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
CodeEditorView            I   content_main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
StopWatch                 D   Action 'ide.editor.previewLayout' completed in 42ms 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
StopWatch                 D   Action 'ide.editor.code.text.undo' completed in 19ms 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
EditorActivity            I   Opening file at index:  1  file:   /storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
CodeEditorView            I   nav_header_main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
StopWatch                 D   Action 'ide.editor.previewLayout' completed in 54ms 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 0 items   
CompletionThread          D   Found 5 items   
CompletionThread          D   Found 0 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 28 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 50 items  (incomplete) 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 31 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 1 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 0 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 0 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 0 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 50 items  (incomplete) 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 50 items  (incomplete) 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 7 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 8 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 8 items   
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
CompletionThread          I   Complete attribute value: 'android:text' 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
XmlCompletionProvider     I   Found 33 resource tables for namespace: http://schemas.android.com/apk/res-auto 
XmlCompletionProvider     I   Found 34 resource tables for namespace: http://schemas.android.com/apk/res/android 
CompletionThread          D   Found 3 items   
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
StopWatch                 D   Action 'ide.editor.code.text.undo' completed in 15ms 
CodeEditorView            I   content_main.xml 
CodeEditorView            I   File was not modified. Skipping save operation. 
ResourceTableRegistry     I   Creating resource table for 1 resource directories 
StopWatch                 D   Action 'ide.editor.previewLayout' completed in 170ms 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
AndroidModule             I   Created 32 resource tables for 32 dependencies of module ':app' 
StopWatch                 D   Action 'ide.uidesigner.showHierarchy' completed in 1ms 
StopWatch                 D   Action 'ide.uidesigner.showXml' completed in 66ms 
LanguageSpecProvider      W   Scheme file 'locals' for type 'xml' not found 
BootClassProvider         D   Indexing boot classpath:  /data/data/com.itsaky.androidide/files/home/.androidide/android.jar 
StopWatch                 D   Action 'ide.editor.code.text.undo' completed in 11ms 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))]) 
EditorActivity            D   [onPause]  Opened files cache reset to OpenedFilesCache(selectedFile=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, allFiles=[OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/content_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0))), OpenedFile(filePath=/storage/emulated/0/AndroidIDEProjects/Boter's SooperDuperApp/app/src/main/res/layout/nav_header_main.xml, selection=Range(start=Position(line=0, column=0, index=0), end=Position(line=0, column=0, index=0)))])
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AButterLamp** [comment] 2023-12-10 15:50
It also happens with the " com.google.android.material.floatingactionbutton.FloatingActionButton" element

**Comment by AButterLamp** [comment] 2023-12-10 20:20
Also the Ui Designer shows elements as being in the top left, but when compiled into an apk, the element is in the centre

**Comment by itsaky** [comment] 2023-12-13 16:16
Only the platform views are supported at the moment. This is a duplicate of #212.

**Closed by itsaky** 2023-12-13 16:16 UTC
Labels: bug
