### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NebexBerzency** [AndroidIDEOfficial/AndroidIDE#652] opened 2022-12-02 19:39 UTC
### What happened?

AndroidIDE crash report
Manufacturer: HUAWEI
Device: BKK-LX2
ABI: arm64-v8a
SDK version: 27
App version: 2.1.3-beta (213)

 

### What's the expected behavior?

Stacktrace: 
java.lang.NullPointerException
	at com.itsaky.androidide.fragments.LogViewFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:19)
	at android.os.Handler.handleCallback(Handler.java:809)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7555)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-12-03 06:27
Probably a duplicate of #605.

**Closed** 2022-12-10 17:32 UTC
Labels: bug
