### ISSUE TITLE
[Bug]: Crash in dark mode

### ISSUE THREAD

**Issue by HDLED1** [AndroidIDEOfficial/AndroidIDE#1101] opened 2023-07-13 21:51 UTC
### What happened?

the app crashes in dark mode select

### What's the expected behavior?

dark mode

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Multilaser
Device: Multilaser_E
ABI: armeabi-v7a
SDK version: 27
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1656)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1685)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6715)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-14 12:07
Duplicate of #870.

**Closed by itsaky** 2023-07-14 12:07 UTC
Labels: bug
