### ISSUE TITLE
When i running Android ide

### ISSUE THREAD

**Issue by Dheerendra939** [AndroidIDEOfficial/AndroidIDE#1315] opened 2023-09-14 15:14 UTC
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2003J15SC
ABI: arm64-v8a
SDK version: 30
App version: v2.5.0-beta (250)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:914)
	at android.content.res.AssetManager.open(AssetManager.java:891)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### What's the expected behavior?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2003J15SC
ABI: arm64-v8a
SDK version: 30
App version: v2.5.0-beta (250)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:914)
	at android.content.res.AssetManager.open(AssetManager.java:891)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2003J15SC
ABI: arm64-v8a
SDK version: 30
App version: v2.5.0-beta (250)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:914)
	at android.content.res.AssetManager.open(AssetManager.java:891)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-09-14 15:32
Your device is `armeabi-v7a`, but you have installed the APK for `arm64-v8a`. Please download the proper variant of the application.

Duplicate of #1121.

**Closed by itsaky** 2023-09-14 15:32 UTC
Labels: bug
