### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by inkwise** [AndroidIDEOfficial/AndroidIDE#1160] opened 2023-07-30 07:47 UTC
AndroidIDE crash report
Manufacturer: vivo
Device: V2158A
ABI: arm64-v8a
SDK version: 30
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2035)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2067)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by itsaky** [comment] 2023-07-30 08:39
Duplicate of #870.

Update AndroidIDE to the latest version.

**Closed by itsaky** 2023-07-30 08:39 UTC
