### ISSUE TITLE
[Bug]: Problem Android IDE Crash

### ISSUE THREAD

**Issue by ZankzaMods** [AndroidIDEOfficial/AndroidIDE#1078] opened 2023-07-09 20:08 UTC
### What happened?

AndroidIDE crash report
Manufacturer: Xiaomi
Device: RedmiNote8Pro
ABI: arm64-v8a
SDK version: 29
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1956)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1988)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

### What's the expected behavior?

I went to compile my project and it crashes and bugs

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-10 04:22
Duplicate of #870.

**Closed by itsaky** 2023-07-10 04:22 UTC
Labels: bug
