### ISSUE TITLE
[Bug]: Crash on implement abstract method inside an Interface

### ISSUE THREAD

**Issue by ThatMG393** [AndroidIDEOfficial/AndroidIDE#939] opened 2023-04-12 11:38 UTC
### What happened?

Crash when I tried to click "Implement Abstract Method(s)" inside an Interface.

```java
addListener(new SomeListener() {
    // Try to run "Implement Abstract Method(s)"
    // Dont type anything
});
```

### What's the expected behavior?

Extracts the abstract methods and put it inside

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A136B
ABI: armeabi-v7a
SDK version: 33
App version: v1.0.0-internal.1+branch.dev.commit.6f49ac2.timestamp.20230405041341 (100)

 Stacktrace: 
java.lang.StringIndexOutOfBoundsException: Column 16 out of bounds. line: 60 , column count (line separator included):6
	at io.github.rosemoe.sora.text.Content.checkLineAndColumn(Content.java:1059)
	at io.github.rosemoe.sora.text.Content.insertInternal(Content.java:357)
	at io.github.rosemoe.sora.text.Content.insert(Content.java:350)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl.lambda$editInEditor$2(IDELanguageClientImpl.java:268)
	at com.itsaky.androidide.lsp.IDELanguageClientImpl$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-04-14 11:13
Duplicate of #916.

**Closed by itsaky** 2023-04-14 11:13 UTC
Labels: bug
