### ISSUE TITLE
Crash on file select

### ISSUE THREAD

**Issue by TheRemakerMan** [AndroidIDEOfficial/AndroidIDE#1503] opened 2023-11-28 04:17 UTC
### What happened?

Just selecting files in tree view 

### What's the expected behavior?

No crash.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : TECNO MOBILE LIMITED
Device : TECNOKG5n

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.hasUnsavedFiles(Unknown Source:36)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.closeFile(Unknown Source:254)
	at com.itsaky.androidide.actions.file.FileTabAction.execAction(Unknown Source:44)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$executeAction$1.invokeSuspend(Unknown Source:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at javac.internal.jrtfs.JrtUtils.resumeCancellableWith(Unknown Source:162)
	at kotlinx.coroutines.AbstractCoroutine.start(Unknown Source:81)
	at kotlin.io.ByteStreamsKt.launch(Unknown Source:48)
	at kotlin.io.ByteStreamsKt.launch$default(Unknown Source:14)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry.executeAction(Unknown Source:31)
	at okhttp3.Dns$$ExternalSyntheticLambda0.onClick(Unknown Source:5)
	at com.itsaky.androidide.actions.internal.DefaultActionsRegistry$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:33)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:147)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1193)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3185)
	at android.widget.AbsListView$3.run(AbsListView.java:4103)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:8011)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:635)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafael2616** [comment] 2023-11-28 05:01
Duplicate of #1498

**Closed** 2023-11-28 06:16 UTC
Labels: bug
