### ISSUE TITLE
[Bug]: AndroidIde gets Stuck

### ISSUE THREAD

**Issue by ranjitsingha** [AndroidIDEOfficial/AndroidIDE#1174] opened 2023-08-04 05:09 UTC
### What happened?

After sometime androidide gets stuck without any reason. And then no button works when clicked. Also note that the app didn't crashed and it stayed stuck there.

### What's the expected behavior?

Should not get stucked

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
I can't open the logs since it was stuck and i had to remove the app and start again.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-08-04 16:24
Duplicate of #1041.

**Closed by itsaky** 2023-08-04 16:24 UTC
Labels: bug
