### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GabrielDEV3** [AndroidIDEOfficial/AndroidIDE#1567] opened 2023-12-19 13:39 UTC
### What happened?

Crashou o app

### What's the expected behavior?

Abrir o terminal

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-A146M

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getOpenedFiles(Unknown Source:29)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.saveOpenedFiles(Unknown Source:0)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.onPause(Unknown Source:11)
	at android.app.Activity.performPause(Activity.java:8778)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1585)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5707)
 Caused by: java.lang.RuntimeException: Unable to pause activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5717)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5668)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5620)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-21 05:37
Duplicate of #1498.

**Closed by itsaky** 2023-12-21 05:37 UTC
Labels: bug
