### ISSUE TITLE
[Feature]: heeellp pliis

### ISSUE THREAD

**Issue by Danielntts** [AndroidIDEOfficial/AndroidIDE#1424] opened 2023-11-05 05:07 UTC
### Feature description

Executar tarefas : [assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Observed package id 'tools' in inconsistent location '/data/data/com.itsaky.androidide/files/home/android-sdk/cmdline-tools/latest' (Expected '/data/data/com.itsaky.androidide/files/home/android-sdk/tools')

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Failed to find Build Tools revision 33.0.3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sb-codz** [comment] 2023-11-05 06:02
change build tool version 33.0.3 to 33.0.2
because 33.0.3 currently not available.

**Comment by itsaky** [comment] 2023-11-05 06:11
Duplicate of #1418.

**Closed by itsaky** 2023-11-05 06:11 UTC
Labels: feature
