### ISSUE TITLE
[Feature]: Auto save

### ISSUE THREAD

**Issue by appt2** [AndroidIDEOfficial/AndroidIDE#1362] opened 2023-10-03 10:53 UTC
### Feature description

@itsaky can you adding Autosave?

### What version of AndroidIDE you're using?

v2.5.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-10-03 12:24
Duplicate of #1261.

An experimental auto save feature is already available and can be enabled from preferences. A proper implementation is planned for v2.7.0-beta.

**Closed by itsaky** 2023-10-03 12:24 UTC
Labels: feature
