### ISSUE TITLE
[Feature]: Enhancement Request: Add Rename Refactoring Feature for Mobile-Based Android IDE.

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#1476] opened 2023-11-17 02:04 UTC
### Feature description

* Description: I've been actively using the Android IDE on my mobile device for several months and have found it to be a valuable tool for on-the-go development. However, one aspect that has been noticeably lacking is the Rename Refactoring feature.
* Expected Behavior: I would like to request the addition of the Rename Refactoring feature to the mobile-based Android IDE. Based on my experience, there have been instances where this feature would have significantly improved efficiency. This enhancement aims to automatically update all instances, references, import statements, and folder or package names when a class is renamed.
* Rationale: My day-to-day coding involves working on projects with multiple folders and packages. The absence of the Rename Refactoring feature on the mobile IDE has led to manual adjustments and potential issues. Introducing this feature would not only align the mobile IDE with its desktop counterpart but also enhance the overall coding experience.
* Additional Information: I've encountered scenarios where having the Rename Refactoring feature, with consideration for folders or packages, on the mobile Android IDE would have been immensely beneficial. This enhancement is not just a convenience but a practical necessity for developers who rely on mobile platforms for coding. 
* Thank you for considering this feature request.

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-11-17 08:47
Duplicate of #502.

**Closed by itsaky** 2023-11-17 08:47 UTC
Labels: feature
