### ISSUE TITLE
AndroidIDE Crash Report


### ISSUE THREAD

**Issue by BCBLearning** [AndroidIDEOfficial/AndroidIDE#1878] opened 2024-08-17 21:06 UTC
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 33
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : OPPO
Device : CPH2219

Stacktrace:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1351)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:405)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1595)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1357)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1323)
	at io.github.rosemoe.sora.widget.base.EditorPopupWindow.applyWindowAttributes(Unknown Source:152)
	at com.itsaky.androidide.editor.ui.AbstractPopupWindow.show(Unknown Source:25)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.show(Unknown Source:224)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu.displayWindow(Unknown Source:168)
	at com.itsaky.androidide.editor.ui.EditorActionsMenu$$ExternalSyntheticLambda1.run(Unknown Source:21)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by itsaky** [comment] 2024-09-01 11:40
Duplicate of #1752

**Closed as not planned by itsaky** 2024-09-01 11:40 UTC
