### ISSUE TITLE
[Feature]: Unicode support

### ISSUE THREAD

**Issue by pavel5750cz** [AndroidIDEOfficial/AndroidIDE#1558] opened 2023-12-16 09:19 UTC
### Feature description

I cannot type á é í ó ú with samsung keyboard

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-12-16 10:11
Duplicate of #1438.

**Closed by itsaky** 2023-12-16 10:11 UTC
Labels: feature
