### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by azmatjan520** [AndroidIDEOfficial/AndroidIDE#840] opened 2023-03-05 17:22 UTC
### What happened?

AndroidIDE crash report
Manufacturer: OPPO
Device: PECM30
ABI: arm64-v8a
SDK version: 31
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2232)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2265)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### What's the expected behavior?

AndroidIDE UIMode

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: PECM30
ABI: arm64-v8a
SDK version: 31
App version: v2.3.0-beta (230)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2232)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2265)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-03-05 17:25
Duplicate of #839.

**Closed by itsaky** 2023-03-05 17:25 UTC
Labels: bug
