### ISSUE TITLE
[Bug]: Crash when navigating to a file that has errors

### ISSUE THREAD

**Issue by Allosh87** [AndroidIDEOfficial/AndroidIDE#467] opened 2022-09-24 21:07 UTC
### What happened?

- Navigating to a file that contains errors.

### What's the expected behavior?

IDE crashed!

### What version of AndroidIDE you're using?

v2.1.1

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-A305F
App version: 2.1.1-beta (211)

 Stacktrace: 
java.lang.ArrayIndexOutOfBoundsException: length=128; index=-1
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:252)
	at io.github.rosemoe.sora.widget.layout.LineBreakLayout.getCharLayoutOffset(LineBreakLayout.java:178)
	at io.github.rosemoe.sora.widget.CursorBlink.run(CursorBlink.java:81)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2022-09-25 11:23
Duplicate of #195.

Look into the issues before checking the duplicate checkbox.

**Closed by itsaky** 2022-09-25 11:23 UTC
Labels: bug
