### ISSUE TITLE
[Bug]: Crash when closing project

### ISSUE THREAD

**Issue by MikuMeow0831** [AndroidIDEOfficial/AndroidIDE#1149] opened 2023-07-25 02:20 UTC
### What happened?

Crash occurred when I closed my project in the navigation bar

### What's the expected behavior?

Software crash

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: OPPO
Device: PCKM00
ABI: arm64-v8a
SDK version: 30
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4676)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@adb26f: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4696)
	at android.app.ActivityThread.access$2000(ActivityThread.java:293)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8283)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-25 18:02
Duplicate of #1132.

**Closed by itsaky** 2023-07-25 18:02 UTC
Labels: bug
