### ISSUE TITLE
libic.so.6 file not found [Bug]: 

### ISSUE THREAD

**Issue by mohammad-ayan-008** [AndroidIDEOfficial/AndroidIDE#989] opened 2023-05-26 13:42 UTC
### What happened?

room database error

### What's the expected behavior?

It should have been worked w well

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
Task :app:compileDebugJavaWithJavac
Failed to load native library:sqlite-3.25.2-1cd5fbb4-345d-4e88-abd2-1d23cac56f0d-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.25.2-1cd5fbb4-345d-4e88-abd2-1d23cac56f0d-libsqlitejdbc.so: dlopen failed: library "libc.so.6" not found
Failed to load native library:sqlite-3.25.2-e59ccc91-708e-4369-8cb9-c502e59e62dd-libsqlitejdbc.so. osinfo: Linux/armv7
java.lang.UnsatisfiedLinkError: /data/data/com.itsaky.androidide/files/usr/tmp/sqlite-3.25.2-e59ccc91-708e-4369-8cb9-c502e59e62dd-libsqlitejdbc.so: dlopen failed: library "libc.so.6" not found
/storage/emulated/0/AndroidIDEProjects/Foodie/app/src/main/java/com/example/foodie/Expense.java:12: error: Cannot find getter for field.
    private int id;
                ^
/storage/emulated/0/AndroidIDEProjects/Foodie/app/src/main/java/com/example/foodie/Expense.java:14: error: Cannot find getter for field.
    private String Info;
                   ^
/storage/emulated/0/AndroidIDEProjects/Foodie/app/src/main/java/com/example/foodie/Expense.java:12: error: Cannot find setter for field.
    private int id;
                ^
/storage/emulated/0/AndroidIDEProjects/Foodie/app/src/main/java/com/example/foodie/Expense.java:14: error: Cannot find setter for field.
    private String Info;
                   ^
4 errors

> Task :app:compileDebugJavaWithJavac FAILED

> Task :app:initializeIDEProject
>>> PROJECT INITIALIZED <<<

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.UnsatisfiedLinkError: 'void org.sqlite.core.NativeDB._open_utf8(byte[], int)'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-05-26 18:36
Duplicate of #827.

**Closed by itsaky** 2023-05-26 18:36 UTC
Labels: bug
