### ISSUE TITLE
Not Build Cordova[Bug]: 

### ISSUE THREAD

**Issue by Kotlinjajs** [AndroidIDEOfficial/AndroidIDE#1065] opened 2023-07-06 13:01 UTC
### What happened?

The project was built with Cordova، not implemented

### What's the expected behavior?

Execute the project correctly

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: HUAWEI
Device: JAT-L29
ABI: armeabi-v7a
SDK version: 28
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

### Duplicate issues

- [x] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-08 17:18
Duplicate of #870.

**Closed by itsaky** 2023-07-08 17:18 UTC
Labels: bug
