### ISSUE TITLE
[Feature]: Kotlin Code Helper

### ISSUE THREAD

**Issue by dev-Maghraby** [AndroidIDEOfficial/AndroidIDE#1798] opened 2024-05-04 20:21 UTC
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Kotlin code suggestions and auto complete.

### Use Case

null

### Benefits

It improves user's coding productivity levels.

**Comment by mohammad-ayan-008** [comment] 2024-05-06 14:15
It's under development it will take time

**Comment by itsaky** [comment] 2024-05-06 17:46
Duplicate of #211

**Closed as not planned by itsaky** 2024-05-06 17:46 UTC
Labels: duplicate, feature
