### ISSUE TITLE
[Bug]: GradleBuildService instance has been released

### ISSUE THREAD

**Issue by vova7878** [AndroidIDEOfficial/AndroidIDE#1034] opened 2023-06-11 14:22 UTC
### What happened?

Application crash

### What's the expected behavior?

I clicked on the notification about the end of the build

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: MIMAX3
ABI: arm64-v8a
SDK version: 28
App version: v2.4.1-beta (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:40)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1740)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1772)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-06-15 17:20
Duplicate of #870.

**Closed by itsaky** 2023-06-15 17:20 UTC
Labels: bug
