### ISSUE TITLE
[Bug]: Crash after changing to dark mode

### ISSUE THREAD

**Issue by TIMISONG-dev** [AndroidIDEOfficial/AndroidIDE#1168] opened 2023-07-30 20:22 UTC
### What happened?

I'm changed dark mode in quick settings and IDE crashed

### What's the expected behavior?

-

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2012K11AG
ABI: arm64-v8a
SDK version: 33
App version: v2.5.1-beta (251)

 Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.itsaky.androidide.services.log.MultiLogSenderHandler.close(Unknown Source:23)
	at com.itsaky.androidide.services.log.LogReceiverImpl.close(Unknown Source:2)
	at com.itsaky.androidide.services.log.LogReceiverService.onDestroy(Unknown Source:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4683)
 Caused by: java.lang.RuntimeException: Unable to stop service com.itsaky.androidide.services.log.LogReceiverService@bd6488d: java.util.ConcurrentModificationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4703)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-08-04 16:22
Duplicate of #1132.

**Closed by itsaky** 2023-08-04 16:23 UTC
Labels: bug
