### ISSUE TITLE
[Bug]: App Crash 

### ISSUE THREAD

**Issue by TieuuLann** [AndroidIDEOfficial/AndroidIDE#1577] opened 2023-12-23 20:02 UTC
AndroidIDE Crash Report
Version : v2.6.1-beta (261)
CI Build : true
Branch : main
Commit : 8ac221c83
Variant : arm64-v8a (release)
SDK Version : 30
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : RedmiNote8Pro

Stacktrace:
java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.getEditorForFile(Unknown Source:28)
	at com.itsaky.androidide.activities.editor.EditorHandlerActivity.closeAll(Unknown Source:43)
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.onDestroy(Unknown Source:75)
	at android.app.Activity.performDestroy(Activity.java:8428)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5276)
 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.itsaky.androidide/com.itsaky.androidide.activities.editor.EditorActivityKt}: java.lang.NullPointerException: null cannot be cast to non-null type com.itsaky.androidide.ui.CodeEditorView
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5291)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5320)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by itsaky** [comment] 2023-12-24 02:55
Duplicate of #1498.

**Closed by itsaky** 2023-12-24 02:55 UTC
Labels: bug
