### ISSUE TITLE
Build Successful but app crashed V2.3

### ISSUE THREAD

**Issue by b4h3r4id** [AndroidIDEOfficial/AndroidIDE#853] opened 2023-03-11 16:38 UTC
### What happened?

I 'quick run' my project, it says build successful in the notification panel and then the app crashes

### What's the expected behavior?

build successful but eftsoon app crashed

### What version of AndroidIDE you're using?

v2.3.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: M2003J6B2G
ABI: arm64-v8a
SDK version: 33
App version: v2.3.0-beta (230)

 Stacktrace: 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.itsaky.androidide.utilcode.fileprovider/... typ=application/vnd.android.package-archive flg=0x10000001 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2206)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1841)
	at android.app.Activity.startActivityForResult(Activity.java:5616)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:5569)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:6087)
	at android.app.Activity.startActivity(Activity.java:6054)
	at com.itsaky.androidide.utils.ApkInstaller.installApk(ApkInstaller.kt:184)
	at com.itsaky.androidide.actions.build.AssembleDebugAction$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:65)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-03-12 03:40
Check if the issue is fixed in the [latest build](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/runs/4395587292).

**Closed** 2023-03-15 12:24 UTC
Labels: bug
