### ISSUE TITLE
[Bug]: Unexpected shutdown when exiting and re-entering the application.

### ISSUE THREAD

**Issue by esalessandrxx** [AndroidIDEOfficial/AndroidIDE#943] opened 2023-04-13 13:37 UTC
### What happened?

Leaving the application to go to another app and returning to AndroidIDE causes the error that I shared.

`v2.4.1 (debug builds)`

### What's the expected behavior?

Returning to the application without any errors occurring.

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: samsung
Device: SM-G781V
ABI: arm64-v8a
SDK version: 33
App version: v2.4.1-beta.internal.1+branch.dev.commit.852c75e.timestamp.20230413030516 (241)

 Stacktrace: 
java.lang.IllegalStateException: GradleBuildService instance has been released
	at com.itsaky.androidide.services.builder.GradleServiceBinder.getService(GradleServiceBinder.kt:35)
	at com.itsaky.androidide.services.builder.GradleBuildServiceConnnection.onServiceConnected(GradleBuildServiceConnnection.kt:37)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2348)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2381)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-04-13 18:47
Duplicate of #870.

**Closed by itsaky** 2023-04-13 18:47 UTC
Labels: bug
