### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by ILariy357** [AndroidIDEOfficial/AndroidIDE#1151] opened 2023-07-25 13:10 UTC
### What happened?

Terminal not working

### What's the expected behavior?

Fix please

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Relevant log output

```shell
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi5Plus
ABI: arm64-v8a
SDK version: 27
App version: v2.5.0-beta (250)

 Stacktrace: 
java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:378)
	at android.content.res.AssetManager.open(AssetManager.java:352)
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:117)
 Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at openjdk.tools.javac.util.Log$$ExternalSyntheticLambda1.run(Unknown Source:761)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1661)
 Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: data/arm64-v8a/bootstrap.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:276)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:282)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1664)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1653)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment] 2023-07-25 17:59
Duplicate of #1121.

**Closed by itsaky** 2023-07-25 17:59 UTC
Labels: bug
