### ISSUE TITLE
Androidide crashes when switching between apps and resizing apps(split screen) on Galaxy s23 ultra 

### ISSUE THREAD

**Issue by Josh-Reimer** [AndroidIDEOfficial/AndroidIDE#1773] opened 2024-03-22 16:13 UTC
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 34
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : samsung
Device : SM-S918W

Stacktrace:
java.lang.IllegalStateException: Activity has been destroyed
	at com.itsaky.androidide.activities.editor.BaseEditorActivity.getBinding(Unknown Source:13)
	at com.blankj.utilcode.util.KeyboardUtils$2.onGlobalLayout(Unknown Source:25)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1165)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4535)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3239)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11197)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
	at android.view.Choreographer.doFrame(Choreographer.java:1055)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

    I had just created a project and then was switching to another app for something and then when I came back it showed the above error. I am on android 14(oneUI 6) on a Galaxy s23 ultra.

**Comment by itsaky** [comment] 2024-03-29 04:38
Duplicate of #1717

**Closed as not planned by itsaky** 2024-03-29 04:38 UTC
Labels: bug, duplicate
