### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Wjxfi** [AndroidIDEOfficial/AndroidIDE#1862] opened 2024-07-28 16:09 UTC
Unsupported method: ModelBuilderParameter.getDontBuildHostTestRuntimeClasspath().

I really want to do this, please help me fix it

Libretube, GreenStash, IYPS - tried

**Comment by itsaky** [comment] 2024-07-28 16:14
Duplicate of #1837

**Closed as not planned by itsaky** 2024-07-28 16:14 UTC
