### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by H1p4zdev** [AndroidIDEOfficial/AndroidIDE#1332] opened 2023-09-22 19:26 UTC
### What happened?

Vai yeh Android 11 mein work Nahi Kar Raha he. Build e Nahi ho Raha he .
All versions I tried but it still not working. Build process is not completing in any new or existing project . @

### What's the expected behavior?

@itsaky #
![Screenshot_2023-09-22-23-35-15-829_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/138879774/e320c5f2-bbf3-4ad1-8d1b-0e1d80d62e32)

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment] 2023-09-23 06:32
Go to app/build.gradle then change `buildToolsVersion` to '33.0.1'

**Comment by itsaky** [comment] 2023-09-23 07:03
Duplicate of #1232.

**Closed by itsaky** 2023-09-23 07:03 UTC
Labels: bug

**Comment by H1p4zdev** [comment] 2023-09-23 10:50
Run tasks : [:clean, :cleanIdea]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.5.3-beta-b1aafdf7e-SNAPSHOT') to variant 'debug' of project ':app'

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match ':cleanIdea' as task 'cleanIdea' not found in root project 'Let's Play'.

* Try:
> Run gradle tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by H1p4zdev** [comment] 2023-09-23 11:01
Run tasks : [:app:assembleDebug]

> Configure project :app
WARNING: The option setting 'android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/home/.androidide/aapt2' is experimental.
Adding LogSender dependency (version '2.5.3-beta-b1aafdf7e-SNAPSHOT') to variant 'debug' of project ':app'

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:packageDebugResources UP-TO-DATE
> Task :app:parseDebugLocalResources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE

> Task :app:mergeDebugResources
/data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/b963be45d498a200089859b68d10c6ee/transformed/material-1.9.0/res/values/values.xml:1255:4: Failed to flatten XML for resource 'app_name' with error: Invalid unicode escape sequence in string
"{str}"
/data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/b963be45d498a200089859b68d10c6ee/transformed/material-1.9.0/res/values/values.xml:1255:4: string/app_name does not contain a valid string resource.

> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest
> Task :app:mergeDebugResources FAILED
> Task :app:processDebugManifest

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /storage/emulated/0/AndroidIDEProjects/Let's Play/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@2fc4f107.). Check logs for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
12 actionable tasks: 3 executed, 9 up-to-date
