### ISSUE TITLE
AndroidIDE crashed after using accent symbols

### ISSUE THREAD

**Issue by devicewhite** [AndroidIDEOfficial/AndroidIDE#1724] opened 2024-02-15 02:26 UTC
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Whenever I try to use an accent in strings or bit operations, the Android IDE crashes. However, this only happens if a physical keyboard is used. As a Brazilian citizen, my keyboard is type ABNT2, which is a type of keyboard with "Ç"

### Expected behavior

It should display the symbol correctly, just like all other IDE's

### Version name

Version : v2.7.1-beta (27102)

### Download source

GitHub

### Relevant log output

```bash
AndroidIDE Crash Report
Version : v2.7.1-beta (27102)
CI Build : true
Branch : main
Commit : 55bb46b31
Variant : arm64-v8a (release)
Build type : OFFICIAL
F-Droid Build : false
F-Droid Version : null
F-Droid Version code : -1
SDK Version : 29
Supported ABIs : [arm64-v8a, armeabi-v7a, armeabi]
Manufacturer : Xiaomi
Device : MI8Lite

Stacktrace:
java.lang.IllegalArgumentException
	at java.lang.Character.toChars(Character.java:5207)
	at io.github.rosemoe.sora.widget.CodeEditor.onKeyDown(Unknown Source:742)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2820)
	at android.view.View.dispatchKeyEvent(View.java:13419)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1948)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:486)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1843)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4019)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(Unknown Source:0)
	at androidx.core.view.WindowCompat.dispatchKeyEvent(Unknown Source:10)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(Unknown Source:18)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(Unknown Source:22)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(Unknown Source:19)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:389)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5563)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5431)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4989)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5095)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4963)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5152)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4989)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4963)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4936)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4989)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5128)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5291)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3071)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2614)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2605)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3048)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by itsaky** [comment] 2024-02-15 16:56
Duplicate of #1495

**Closed as not planned by itsaky** 2024-02-15 16:56 UTC
Labels: bug, duplicate
